# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - typecheck
  disable:
    - errcheck      # Error return value шалгалтыг идэвхгүй болгох
    - unused        # Unused function шалгалтыг идэвхгүй болгох
    - ineffassign   # Ineffectual assignment шалгалтыг идэвхгүй болгох

linters-settings:
  govet:
    check-shadowing: false
  
  gofmt:
    simplify: true
  
  gosimple:
    checks: []  # S1039 гэх мэт шалгалтуудыг хаах

issues:
  # Ignore эдгээр алдаануудыг бүгд
  exclude-rules:
    # Ignore errcheck for specific patterns
    - linters:
        - errcheck
      text: "Error return value of"
    
    # Ignore unused functions
    - linters:
        - unused
      text: "is unused"
    
    # Ignore ineffassign
    - linters:
        - ineffassign
      text: "ineffectual assignment"
    
    # Ignore gosimple S1039 (unnecessary fmt.Sprintf)
    - linters:
        - gosimple
      text: "S1039"
  
  # Maximum issues count per linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0
  
  # Exclude common false positives
  exclude-use-default: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
