// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newLessonCategory(db *gorm.DB, opts ...gen.DOOption) lessonCategory {
	_lessonCategory := lessonCategory{}

	_lessonCategory.lessonCategoryDo.UseDB(db, opts...)
	_lessonCategory.lessonCategoryDo.UseModel(&model.LessonCategory{})

	tableName := _lessonCategory.lessonCategoryDo.TableName()
	_lessonCategory.ALL = field.NewAsterisk(tableName)
	_lessonCategory.ID = field.NewInt(tableName, "id")
	_lessonCategory.ParentID = field.NewInt(tableName, "parent_id")
	_lessonCategory.NameEn = field.NewString(tableName, "name_en")
	_lessonCategory.NameMn = field.NewString(tableName, "name_mn")
	_lessonCategory.Description = field.NewString(tableName, "description")
	_lessonCategory.Icon = field.NewString(tableName, "icon")
	_lessonCategory.Color = field.NewString(tableName, "color")
	_lessonCategory.SortOrder = field.NewInt(tableName, "sort_order")
	_lessonCategory.IsActive = field.NewBool(tableName, "is_active")
	_lessonCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_lessonCategory.Emoji = field.NewString(tableName, "emoji")
	_lessonCategory.Children = lessonCategoryHasManyChildren{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Children", "model.LessonCategory"),
	}

	_lessonCategory.fillFieldMap()

	return _lessonCategory
}

type lessonCategory struct {
	lessonCategoryDo lessonCategoryDo

	ALL         field.Asterisk
	ID          field.Int
	ParentID    field.Int
	NameEn      field.String
	NameMn      field.String
	Description field.String
	Icon        field.String
	Color       field.String
	SortOrder   field.Int
	IsActive    field.Bool
	CreatedAt   field.Time
	Emoji       field.String
	Children    lessonCategoryHasManyChildren

	fieldMap map[string]field.Expr
}

func (l lessonCategory) Table(newTableName string) *lessonCategory {
	l.lessonCategoryDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lessonCategory) As(alias string) *lessonCategory {
	l.lessonCategoryDo.DO = *(l.lessonCategoryDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lessonCategory) updateTableName(table string) *lessonCategory {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt(table, "id")
	l.ParentID = field.NewInt(table, "parent_id")
	l.NameEn = field.NewString(table, "name_en")
	l.NameMn = field.NewString(table, "name_mn")
	l.Description = field.NewString(table, "description")
	l.Icon = field.NewString(table, "icon")
	l.Color = field.NewString(table, "color")
	l.SortOrder = field.NewInt(table, "sort_order")
	l.IsActive = field.NewBool(table, "is_active")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.Emoji = field.NewString(table, "emoji")

	l.fillFieldMap()

	return l
}

func (l *lessonCategory) WithContext(ctx context.Context) *lessonCategoryDo {
	return l.lessonCategoryDo.WithContext(ctx)
}

func (l lessonCategory) TableName() string { return l.lessonCategoryDo.TableName() }

func (l lessonCategory) Alias() string { return l.lessonCategoryDo.Alias() }

func (l lessonCategory) Columns(cols ...field.Expr) gen.Columns {
	return l.lessonCategoryDo.Columns(cols...)
}

func (l *lessonCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lessonCategory) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 12)
	l.fieldMap["id"] = l.ID
	l.fieldMap["parent_id"] = l.ParentID
	l.fieldMap["name_en"] = l.NameEn
	l.fieldMap["name_mn"] = l.NameMn
	l.fieldMap["description"] = l.Description
	l.fieldMap["icon"] = l.Icon
	l.fieldMap["color"] = l.Color
	l.fieldMap["sort_order"] = l.SortOrder
	l.fieldMap["is_active"] = l.IsActive
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["emoji"] = l.Emoji

}

func (l lessonCategory) clone(db *gorm.DB) lessonCategory {
	l.lessonCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	l.Children.db = db.Session(&gorm.Session{Initialized: true})
	l.Children.db.Statement.ConnPool = db.Statement.ConnPool
	return l
}

func (l lessonCategory) replaceDB(db *gorm.DB) lessonCategory {
	l.lessonCategoryDo.ReplaceDB(db)
	l.Children.db = db.Session(&gorm.Session{})
	return l
}

type lessonCategoryHasManyChildren struct {
	db *gorm.DB

	field.RelationField
}

func (a lessonCategoryHasManyChildren) Where(conds ...field.Expr) *lessonCategoryHasManyChildren {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a lessonCategoryHasManyChildren) WithContext(ctx context.Context) *lessonCategoryHasManyChildren {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a lessonCategoryHasManyChildren) Session(session *gorm.Session) *lessonCategoryHasManyChildren {
	a.db = a.db.Session(session)
	return &a
}

func (a lessonCategoryHasManyChildren) Model(m *model.LessonCategory) *lessonCategoryHasManyChildrenTx {
	return &lessonCategoryHasManyChildrenTx{a.db.Model(m).Association(a.Name())}
}

func (a lessonCategoryHasManyChildren) Unscoped() *lessonCategoryHasManyChildren {
	a.db = a.db.Unscoped()
	return &a
}

type lessonCategoryHasManyChildrenTx struct{ tx *gorm.Association }

func (a lessonCategoryHasManyChildrenTx) Find() (result []*model.LessonCategory, err error) {
	return result, a.tx.Find(&result)
}

func (a lessonCategoryHasManyChildrenTx) Append(values ...*model.LessonCategory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a lessonCategoryHasManyChildrenTx) Replace(values ...*model.LessonCategory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a lessonCategoryHasManyChildrenTx) Delete(values ...*model.LessonCategory) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a lessonCategoryHasManyChildrenTx) Clear() error {
	return a.tx.Clear()
}

func (a lessonCategoryHasManyChildrenTx) Count() int64 {
	return a.tx.Count()
}

func (a lessonCategoryHasManyChildrenTx) Unscoped() *lessonCategoryHasManyChildrenTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type lessonCategoryDo struct{ gen.DO }

func (l lessonCategoryDo) Debug() *lessonCategoryDo {
	return l.withDO(l.DO.Debug())
}

func (l lessonCategoryDo) WithContext(ctx context.Context) *lessonCategoryDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lessonCategoryDo) ReadDB() *lessonCategoryDo {
	return l.Clauses(dbresolver.Read)
}

func (l lessonCategoryDo) WriteDB() *lessonCategoryDo {
	return l.Clauses(dbresolver.Write)
}

func (l lessonCategoryDo) Session(config *gorm.Session) *lessonCategoryDo {
	return l.withDO(l.DO.Session(config))
}

func (l lessonCategoryDo) Clauses(conds ...clause.Expression) *lessonCategoryDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lessonCategoryDo) Returning(value interface{}, columns ...string) *lessonCategoryDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lessonCategoryDo) Not(conds ...gen.Condition) *lessonCategoryDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lessonCategoryDo) Or(conds ...gen.Condition) *lessonCategoryDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lessonCategoryDo) Select(conds ...field.Expr) *lessonCategoryDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lessonCategoryDo) Where(conds ...gen.Condition) *lessonCategoryDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lessonCategoryDo) Order(conds ...field.Expr) *lessonCategoryDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lessonCategoryDo) Distinct(cols ...field.Expr) *lessonCategoryDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lessonCategoryDo) Omit(cols ...field.Expr) *lessonCategoryDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lessonCategoryDo) Join(table schema.Tabler, on ...field.Expr) *lessonCategoryDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lessonCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *lessonCategoryDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lessonCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *lessonCategoryDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lessonCategoryDo) Group(cols ...field.Expr) *lessonCategoryDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lessonCategoryDo) Having(conds ...gen.Condition) *lessonCategoryDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lessonCategoryDo) Limit(limit int) *lessonCategoryDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lessonCategoryDo) Offset(offset int) *lessonCategoryDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lessonCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *lessonCategoryDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lessonCategoryDo) Unscoped() *lessonCategoryDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lessonCategoryDo) Create(values ...*model.LessonCategory) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lessonCategoryDo) CreateInBatches(values []*model.LessonCategory, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lessonCategoryDo) Save(values ...*model.LessonCategory) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lessonCategoryDo) First() (*model.LessonCategory, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonCategory), nil
	}
}

func (l lessonCategoryDo) Take() (*model.LessonCategory, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonCategory), nil
	}
}

func (l lessonCategoryDo) Last() (*model.LessonCategory, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonCategory), nil
	}
}

func (l lessonCategoryDo) Find() ([]*model.LessonCategory, error) {
	result, err := l.DO.Find()
	return result.([]*model.LessonCategory), err
}

func (l lessonCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LessonCategory, err error) {
	buf := make([]*model.LessonCategory, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lessonCategoryDo) FindInBatches(result *[]*model.LessonCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lessonCategoryDo) Attrs(attrs ...field.AssignExpr) *lessonCategoryDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lessonCategoryDo) Assign(attrs ...field.AssignExpr) *lessonCategoryDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lessonCategoryDo) Joins(fields ...field.RelationField) *lessonCategoryDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lessonCategoryDo) Preload(fields ...field.RelationField) *lessonCategoryDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lessonCategoryDo) FirstOrInit() (*model.LessonCategory, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonCategory), nil
	}
}

func (l lessonCategoryDo) FirstOrCreate() (*model.LessonCategory, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonCategory), nil
	}
}

func (l lessonCategoryDo) FindByPage(offset int, limit int) (result []*model.LessonCategory, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lessonCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lessonCategoryDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lessonCategoryDo) Delete(models ...*model.LessonCategory) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lessonCategoryDo) withDO(do gen.Dao) *lessonCategoryDo {
	l.DO = *do.(*gen.DO)
	return l
}
