// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newUserDataAccessLog(db *gorm.DB, opts ...gen.DOOption) userDataAccessLog {
	_userDataAccessLog := userDataAccessLog{}

	_userDataAccessLog.userDataAccessLogDo.UseDB(db, opts...)
	_userDataAccessLog.userDataAccessLogDo.UseModel(&model.UserDataAccessLog{})

	tableName := _userDataAccessLog.userDataAccessLogDo.TableName()
	_userDataAccessLog.ALL = field.NewAsterisk(tableName)
	_userDataAccessLog.ID = field.NewUint(tableName, "id")
	_userDataAccessLog.UserID = field.NewUint(tableName, "user_id")
	_userDataAccessLog.AccessedByID = field.NewUint(tableName, "accessed_by_id")
	_userDataAccessLog.AccessType = field.NewString(tableName, "access_type")
	_userDataAccessLog.TableName_ = field.NewString(tableName, "table_name")
	_userDataAccessLog.RecordID = field.NewUint(tableName, "record_id")
	_userDataAccessLog.AccessReason = field.NewString(tableName, "access_reason")
	_userDataAccessLog.IPAddress = field.NewString(tableName, "ip_address")
	_userDataAccessLog.UserAgent = field.NewString(tableName, "user_agent")
	_userDataAccessLog.SessionID = field.NewUint(tableName, "session_id")
	_userDataAccessLog.AccessedAt = field.NewTime(tableName, "accessed_at")
	_userDataAccessLog.User = userDataAccessLogBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.Users"),
		Gamification: struct {
			field.RelationField
			Level struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Gamification", "model.UserGamification"),
			Level: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Gamification.Level", "model.UserLevels"),
			},
		},
	}

	_userDataAccessLog.AccessedBy = userDataAccessLogBelongsToAccessedBy{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AccessedBy", "model.Users"),
		Gamification: struct {
			field.RelationField
			Level struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("AccessedBy.Gamification", "model.UserGamification"),
			Level: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AccessedBy.Gamification.Level", "model.UserLevels"),
			},
		},
	}

	_userDataAccessLog.Session = userDataAccessLogBelongsToSession{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Session", "model.UserSessions"),
		User: struct {
			field.RelationField
			Gamification struct {
				field.RelationField
				Level struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Session.User", "model.Users"),
			Gamification: struct {
				field.RelationField
				Level struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Session.User.Gamification", "model.UserGamification"),
				Level: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Session.User.Gamification.Level", "model.UserLevels"),
				},
			},
		},
	}

	_userDataAccessLog.fillFieldMap()

	return _userDataAccessLog
}

type userDataAccessLog struct {
	userDataAccessLogDo userDataAccessLogDo

	ALL          field.Asterisk
	ID           field.Uint
	UserID       field.Uint
	AccessedByID field.Uint
	AccessType   field.String
	TableName_   field.String
	RecordID     field.Uint
	AccessReason field.String
	IPAddress    field.String
	UserAgent    field.String
	SessionID    field.Uint
	AccessedAt   field.Time
	User         userDataAccessLogBelongsToUser

	AccessedBy userDataAccessLogBelongsToAccessedBy

	Session userDataAccessLogBelongsToSession

	fieldMap map[string]field.Expr
}

func (u userDataAccessLog) Table(newTableName string) *userDataAccessLog {
	u.userDataAccessLogDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userDataAccessLog) As(alias string) *userDataAccessLog {
	u.userDataAccessLogDo.DO = *(u.userDataAccessLogDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userDataAccessLog) updateTableName(table string) *userDataAccessLog {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint(table, "id")
	u.UserID = field.NewUint(table, "user_id")
	u.AccessedByID = field.NewUint(table, "accessed_by_id")
	u.AccessType = field.NewString(table, "access_type")
	u.TableName_ = field.NewString(table, "table_name")
	u.RecordID = field.NewUint(table, "record_id")
	u.AccessReason = field.NewString(table, "access_reason")
	u.IPAddress = field.NewString(table, "ip_address")
	u.UserAgent = field.NewString(table, "user_agent")
	u.SessionID = field.NewUint(table, "session_id")
	u.AccessedAt = field.NewTime(table, "accessed_at")

	u.fillFieldMap()

	return u
}

func (u *userDataAccessLog) WithContext(ctx context.Context) *userDataAccessLogDo {
	return u.userDataAccessLogDo.WithContext(ctx)
}

func (u userDataAccessLog) TableName() string { return u.userDataAccessLogDo.TableName() }

func (u userDataAccessLog) Alias() string { return u.userDataAccessLogDo.Alias() }

func (u userDataAccessLog) Columns(cols ...field.Expr) gen.Columns {
	return u.userDataAccessLogDo.Columns(cols...)
}

func (u *userDataAccessLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userDataAccessLog) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 14)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["accessed_by_id"] = u.AccessedByID
	u.fieldMap["access_type"] = u.AccessType
	u.fieldMap["table_name"] = u.TableName_
	u.fieldMap["record_id"] = u.RecordID
	u.fieldMap["access_reason"] = u.AccessReason
	u.fieldMap["ip_address"] = u.IPAddress
	u.fieldMap["user_agent"] = u.UserAgent
	u.fieldMap["session_id"] = u.SessionID
	u.fieldMap["accessed_at"] = u.AccessedAt

}

func (u userDataAccessLog) clone(db *gorm.DB) userDataAccessLog {
	u.userDataAccessLogDo.ReplaceConnPool(db.Statement.ConnPool)
	u.User.db = db.Session(&gorm.Session{Initialized: true})
	u.User.db.Statement.ConnPool = db.Statement.ConnPool
	u.AccessedBy.db = db.Session(&gorm.Session{Initialized: true})
	u.AccessedBy.db.Statement.ConnPool = db.Statement.ConnPool
	u.Session.db = db.Session(&gorm.Session{Initialized: true})
	u.Session.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u userDataAccessLog) replaceDB(db *gorm.DB) userDataAccessLog {
	u.userDataAccessLogDo.ReplaceDB(db)
	u.User.db = db.Session(&gorm.Session{})
	u.AccessedBy.db = db.Session(&gorm.Session{})
	u.Session.db = db.Session(&gorm.Session{})
	return u
}

type userDataAccessLogBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	Gamification struct {
		field.RelationField
		Level struct {
			field.RelationField
		}
	}
}

func (a userDataAccessLogBelongsToUser) Where(conds ...field.Expr) *userDataAccessLogBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userDataAccessLogBelongsToUser) WithContext(ctx context.Context) *userDataAccessLogBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userDataAccessLogBelongsToUser) Session(session *gorm.Session) *userDataAccessLogBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a userDataAccessLogBelongsToUser) Model(m *model.UserDataAccessLog) *userDataAccessLogBelongsToUserTx {
	return &userDataAccessLogBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a userDataAccessLogBelongsToUser) Unscoped() *userDataAccessLogBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type userDataAccessLogBelongsToUserTx struct{ tx *gorm.Association }

func (a userDataAccessLogBelongsToUserTx) Find() (result *model.Users, err error) {
	return result, a.tx.Find(&result)
}

func (a userDataAccessLogBelongsToUserTx) Append(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userDataAccessLogBelongsToUserTx) Replace(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userDataAccessLogBelongsToUserTx) Delete(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userDataAccessLogBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a userDataAccessLogBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a userDataAccessLogBelongsToUserTx) Unscoped() *userDataAccessLogBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userDataAccessLogBelongsToAccessedBy struct {
	db *gorm.DB

	field.RelationField

	Gamification struct {
		field.RelationField
		Level struct {
			field.RelationField
		}
	}
}

func (a userDataAccessLogBelongsToAccessedBy) Where(conds ...field.Expr) *userDataAccessLogBelongsToAccessedBy {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userDataAccessLogBelongsToAccessedBy) WithContext(ctx context.Context) *userDataAccessLogBelongsToAccessedBy {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userDataAccessLogBelongsToAccessedBy) Session(session *gorm.Session) *userDataAccessLogBelongsToAccessedBy {
	a.db = a.db.Session(session)
	return &a
}

func (a userDataAccessLogBelongsToAccessedBy) Model(m *model.UserDataAccessLog) *userDataAccessLogBelongsToAccessedByTx {
	return &userDataAccessLogBelongsToAccessedByTx{a.db.Model(m).Association(a.Name())}
}

func (a userDataAccessLogBelongsToAccessedBy) Unscoped() *userDataAccessLogBelongsToAccessedBy {
	a.db = a.db.Unscoped()
	return &a
}

type userDataAccessLogBelongsToAccessedByTx struct{ tx *gorm.Association }

func (a userDataAccessLogBelongsToAccessedByTx) Find() (result *model.Users, err error) {
	return result, a.tx.Find(&result)
}

func (a userDataAccessLogBelongsToAccessedByTx) Append(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userDataAccessLogBelongsToAccessedByTx) Replace(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userDataAccessLogBelongsToAccessedByTx) Delete(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userDataAccessLogBelongsToAccessedByTx) Clear() error {
	return a.tx.Clear()
}

func (a userDataAccessLogBelongsToAccessedByTx) Count() int64 {
	return a.tx.Count()
}

func (a userDataAccessLogBelongsToAccessedByTx) Unscoped() *userDataAccessLogBelongsToAccessedByTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userDataAccessLogBelongsToSession struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
		Gamification struct {
			field.RelationField
			Level struct {
				field.RelationField
			}
		}
	}
}

func (a userDataAccessLogBelongsToSession) Where(conds ...field.Expr) *userDataAccessLogBelongsToSession {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userDataAccessLogBelongsToSession) WithContext(ctx context.Context) *userDataAccessLogBelongsToSession {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userDataAccessLogBelongsToSession) Session(session *gorm.Session) *userDataAccessLogBelongsToSession {
	a.db = a.db.Session(session)
	return &a
}

func (a userDataAccessLogBelongsToSession) Model(m *model.UserDataAccessLog) *userDataAccessLogBelongsToSessionTx {
	return &userDataAccessLogBelongsToSessionTx{a.db.Model(m).Association(a.Name())}
}

func (a userDataAccessLogBelongsToSession) Unscoped() *userDataAccessLogBelongsToSession {
	a.db = a.db.Unscoped()
	return &a
}

type userDataAccessLogBelongsToSessionTx struct{ tx *gorm.Association }

func (a userDataAccessLogBelongsToSessionTx) Find() (result *model.UserSessions, err error) {
	return result, a.tx.Find(&result)
}

func (a userDataAccessLogBelongsToSessionTx) Append(values ...*model.UserSessions) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userDataAccessLogBelongsToSessionTx) Replace(values ...*model.UserSessions) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userDataAccessLogBelongsToSessionTx) Delete(values ...*model.UserSessions) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userDataAccessLogBelongsToSessionTx) Clear() error {
	return a.tx.Clear()
}

func (a userDataAccessLogBelongsToSessionTx) Count() int64 {
	return a.tx.Count()
}

func (a userDataAccessLogBelongsToSessionTx) Unscoped() *userDataAccessLogBelongsToSessionTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userDataAccessLogDo struct{ gen.DO }

func (u userDataAccessLogDo) Debug() *userDataAccessLogDo {
	return u.withDO(u.DO.Debug())
}

func (u userDataAccessLogDo) WithContext(ctx context.Context) *userDataAccessLogDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userDataAccessLogDo) ReadDB() *userDataAccessLogDo {
	return u.Clauses(dbresolver.Read)
}

func (u userDataAccessLogDo) WriteDB() *userDataAccessLogDo {
	return u.Clauses(dbresolver.Write)
}

func (u userDataAccessLogDo) Session(config *gorm.Session) *userDataAccessLogDo {
	return u.withDO(u.DO.Session(config))
}

func (u userDataAccessLogDo) Clauses(conds ...clause.Expression) *userDataAccessLogDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userDataAccessLogDo) Returning(value interface{}, columns ...string) *userDataAccessLogDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userDataAccessLogDo) Not(conds ...gen.Condition) *userDataAccessLogDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userDataAccessLogDo) Or(conds ...gen.Condition) *userDataAccessLogDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userDataAccessLogDo) Select(conds ...field.Expr) *userDataAccessLogDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userDataAccessLogDo) Where(conds ...gen.Condition) *userDataAccessLogDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userDataAccessLogDo) Order(conds ...field.Expr) *userDataAccessLogDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userDataAccessLogDo) Distinct(cols ...field.Expr) *userDataAccessLogDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userDataAccessLogDo) Omit(cols ...field.Expr) *userDataAccessLogDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userDataAccessLogDo) Join(table schema.Tabler, on ...field.Expr) *userDataAccessLogDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userDataAccessLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userDataAccessLogDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userDataAccessLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *userDataAccessLogDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userDataAccessLogDo) Group(cols ...field.Expr) *userDataAccessLogDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userDataAccessLogDo) Having(conds ...gen.Condition) *userDataAccessLogDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userDataAccessLogDo) Limit(limit int) *userDataAccessLogDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userDataAccessLogDo) Offset(offset int) *userDataAccessLogDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userDataAccessLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userDataAccessLogDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userDataAccessLogDo) Unscoped() *userDataAccessLogDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userDataAccessLogDo) Create(values ...*model.UserDataAccessLog) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userDataAccessLogDo) CreateInBatches(values []*model.UserDataAccessLog, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userDataAccessLogDo) Save(values ...*model.UserDataAccessLog) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userDataAccessLogDo) First() (*model.UserDataAccessLog, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDataAccessLog), nil
	}
}

func (u userDataAccessLogDo) Take() (*model.UserDataAccessLog, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDataAccessLog), nil
	}
}

func (u userDataAccessLogDo) Last() (*model.UserDataAccessLog, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDataAccessLog), nil
	}
}

func (u userDataAccessLogDo) Find() ([]*model.UserDataAccessLog, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserDataAccessLog), err
}

func (u userDataAccessLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserDataAccessLog, err error) {
	buf := make([]*model.UserDataAccessLog, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userDataAccessLogDo) FindInBatches(result *[]*model.UserDataAccessLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userDataAccessLogDo) Attrs(attrs ...field.AssignExpr) *userDataAccessLogDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userDataAccessLogDo) Assign(attrs ...field.AssignExpr) *userDataAccessLogDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userDataAccessLogDo) Joins(fields ...field.RelationField) *userDataAccessLogDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userDataAccessLogDo) Preload(fields ...field.RelationField) *userDataAccessLogDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userDataAccessLogDo) FirstOrInit() (*model.UserDataAccessLog, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDataAccessLog), nil
	}
}

func (u userDataAccessLogDo) FirstOrCreate() (*model.UserDataAccessLog, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDataAccessLog), nil
	}
}

func (u userDataAccessLogDo) FindByPage(offset int, limit int) (result []*model.UserDataAccessLog, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userDataAccessLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userDataAccessLogDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userDataAccessLogDo) Delete(models ...*model.UserDataAccessLog) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userDataAccessLogDo) withDO(do gen.Dao) *userDataAccessLogDo {
	u.DO = *do.(*gen.DO)
	return u
}
