// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newUserGamification(db *gorm.DB, opts ...gen.DOOption) userGamification {
	_userGamification := userGamification{}

	_userGamification.userGamificationDo.UseDB(db, opts...)
	_userGamification.userGamificationDo.UseModel(&model.UserGamification{})

	tableName := _userGamification.userGamificationDo.TableName()
	_userGamification.ALL = field.NewAsterisk(tableName)
	_userGamification.ID = field.NewUint(tableName, "id")
	_userGamification.UserID = field.NewUint(tableName, "user_id")
	_userGamification.CurrentLevelID = field.NewInt(tableName, "current_level_id")
	_userGamification.TotalScore = field.NewInt(tableName, "total_score")
	_userGamification.LevelProgress = field.NewInt(tableName, "level_progress")
	_userGamification.CurrentStreak = field.NewInt(tableName, "current_streak")
	_userGamification.LongestStreak = field.NewInt(tableName, "longest_streak")
	_userGamification.LastActivityAt = field.NewTime(tableName, "last_activity_at")
	_userGamification.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userGamification.Level = userGamificationBelongsToLevel{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Level", "model.UserLevels"),
	}

	_userGamification.fillFieldMap()

	return _userGamification
}

type userGamification struct {
	userGamificationDo userGamificationDo

	ALL            field.Asterisk
	ID             field.Uint
	UserID         field.Uint
	CurrentLevelID field.Int
	TotalScore     field.Int
	LevelProgress  field.Int
	CurrentStreak  field.Int
	LongestStreak  field.Int
	LastActivityAt field.Time
	UpdatedAt      field.Time
	Level          userGamificationBelongsToLevel

	fieldMap map[string]field.Expr
}

func (u userGamification) Table(newTableName string) *userGamification {
	u.userGamificationDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userGamification) As(alias string) *userGamification {
	u.userGamificationDo.DO = *(u.userGamificationDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userGamification) updateTableName(table string) *userGamification {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint(table, "id")
	u.UserID = field.NewUint(table, "user_id")
	u.CurrentLevelID = field.NewInt(table, "current_level_id")
	u.TotalScore = field.NewInt(table, "total_score")
	u.LevelProgress = field.NewInt(table, "level_progress")
	u.CurrentStreak = field.NewInt(table, "current_streak")
	u.LongestStreak = field.NewInt(table, "longest_streak")
	u.LastActivityAt = field.NewTime(table, "last_activity_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userGamification) WithContext(ctx context.Context) *userGamificationDo {
	return u.userGamificationDo.WithContext(ctx)
}

func (u userGamification) TableName() string { return u.userGamificationDo.TableName() }

func (u userGamification) Alias() string { return u.userGamificationDo.Alias() }

func (u userGamification) Columns(cols ...field.Expr) gen.Columns {
	return u.userGamificationDo.Columns(cols...)
}

func (u *userGamification) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userGamification) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 10)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["current_level_id"] = u.CurrentLevelID
	u.fieldMap["total_score"] = u.TotalScore
	u.fieldMap["level_progress"] = u.LevelProgress
	u.fieldMap["current_streak"] = u.CurrentStreak
	u.fieldMap["longest_streak"] = u.LongestStreak
	u.fieldMap["last_activity_at"] = u.LastActivityAt
	u.fieldMap["updated_at"] = u.UpdatedAt

}

func (u userGamification) clone(db *gorm.DB) userGamification {
	u.userGamificationDo.ReplaceConnPool(db.Statement.ConnPool)
	u.Level.db = db.Session(&gorm.Session{Initialized: true})
	u.Level.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u userGamification) replaceDB(db *gorm.DB) userGamification {
	u.userGamificationDo.ReplaceDB(db)
	u.Level.db = db.Session(&gorm.Session{})
	return u
}

type userGamificationBelongsToLevel struct {
	db *gorm.DB

	field.RelationField
}

func (a userGamificationBelongsToLevel) Where(conds ...field.Expr) *userGamificationBelongsToLevel {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userGamificationBelongsToLevel) WithContext(ctx context.Context) *userGamificationBelongsToLevel {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userGamificationBelongsToLevel) Session(session *gorm.Session) *userGamificationBelongsToLevel {
	a.db = a.db.Session(session)
	return &a
}

func (a userGamificationBelongsToLevel) Model(m *model.UserGamification) *userGamificationBelongsToLevelTx {
	return &userGamificationBelongsToLevelTx{a.db.Model(m).Association(a.Name())}
}

func (a userGamificationBelongsToLevel) Unscoped() *userGamificationBelongsToLevel {
	a.db = a.db.Unscoped()
	return &a
}

type userGamificationBelongsToLevelTx struct{ tx *gorm.Association }

func (a userGamificationBelongsToLevelTx) Find() (result *model.UserLevels, err error) {
	return result, a.tx.Find(&result)
}

func (a userGamificationBelongsToLevelTx) Append(values ...*model.UserLevels) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userGamificationBelongsToLevelTx) Replace(values ...*model.UserLevels) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userGamificationBelongsToLevelTx) Delete(values ...*model.UserLevels) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userGamificationBelongsToLevelTx) Clear() error {
	return a.tx.Clear()
}

func (a userGamificationBelongsToLevelTx) Count() int64 {
	return a.tx.Count()
}

func (a userGamificationBelongsToLevelTx) Unscoped() *userGamificationBelongsToLevelTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userGamificationDo struct{ gen.DO }

func (u userGamificationDo) Debug() *userGamificationDo {
	return u.withDO(u.DO.Debug())
}

func (u userGamificationDo) WithContext(ctx context.Context) *userGamificationDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userGamificationDo) ReadDB() *userGamificationDo {
	return u.Clauses(dbresolver.Read)
}

func (u userGamificationDo) WriteDB() *userGamificationDo {
	return u.Clauses(dbresolver.Write)
}

func (u userGamificationDo) Session(config *gorm.Session) *userGamificationDo {
	return u.withDO(u.DO.Session(config))
}

func (u userGamificationDo) Clauses(conds ...clause.Expression) *userGamificationDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userGamificationDo) Returning(value interface{}, columns ...string) *userGamificationDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userGamificationDo) Not(conds ...gen.Condition) *userGamificationDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userGamificationDo) Or(conds ...gen.Condition) *userGamificationDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userGamificationDo) Select(conds ...field.Expr) *userGamificationDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userGamificationDo) Where(conds ...gen.Condition) *userGamificationDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userGamificationDo) Order(conds ...field.Expr) *userGamificationDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userGamificationDo) Distinct(cols ...field.Expr) *userGamificationDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userGamificationDo) Omit(cols ...field.Expr) *userGamificationDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userGamificationDo) Join(table schema.Tabler, on ...field.Expr) *userGamificationDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userGamificationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userGamificationDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userGamificationDo) RightJoin(table schema.Tabler, on ...field.Expr) *userGamificationDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userGamificationDo) Group(cols ...field.Expr) *userGamificationDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userGamificationDo) Having(conds ...gen.Condition) *userGamificationDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userGamificationDo) Limit(limit int) *userGamificationDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userGamificationDo) Offset(offset int) *userGamificationDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userGamificationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userGamificationDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userGamificationDo) Unscoped() *userGamificationDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userGamificationDo) Create(values ...*model.UserGamification) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userGamificationDo) CreateInBatches(values []*model.UserGamification, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userGamificationDo) Save(values ...*model.UserGamification) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userGamificationDo) First() (*model.UserGamification, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserGamification), nil
	}
}

func (u userGamificationDo) Take() (*model.UserGamification, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserGamification), nil
	}
}

func (u userGamificationDo) Last() (*model.UserGamification, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserGamification), nil
	}
}

func (u userGamificationDo) Find() ([]*model.UserGamification, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserGamification), err
}

func (u userGamificationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserGamification, err error) {
	buf := make([]*model.UserGamification, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userGamificationDo) FindInBatches(result *[]*model.UserGamification, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userGamificationDo) Attrs(attrs ...field.AssignExpr) *userGamificationDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userGamificationDo) Assign(attrs ...field.AssignExpr) *userGamificationDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userGamificationDo) Joins(fields ...field.RelationField) *userGamificationDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userGamificationDo) Preload(fields ...field.RelationField) *userGamificationDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userGamificationDo) FirstOrInit() (*model.UserGamification, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserGamification), nil
	}
}

func (u userGamificationDo) FirstOrCreate() (*model.UserGamification, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserGamification), nil
	}
}

func (u userGamificationDo) FindByPage(offset int, limit int) (result []*model.UserGamification, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userGamificationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userGamificationDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userGamificationDo) Delete(models ...*model.UserGamification) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userGamificationDo) withDO(do gen.Dao) *userGamificationDo {
	u.DO = *do.(*gen.DO)
	return u
}
