// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newSystemAuditLog(db *gorm.DB, opts ...gen.DOOption) systemAuditLog {
	_systemAuditLog := systemAuditLog{}

	_systemAuditLog.systemAuditLogDo.UseDB(db, opts...)
	_systemAuditLog.systemAuditLogDo.UseModel(&model.SystemAuditLog{})

	tableName := _systemAuditLog.systemAuditLogDo.TableName()
	_systemAuditLog.ALL = field.NewAsterisk(tableName)
	_systemAuditLog.ID = field.NewUint(tableName, "id")
	_systemAuditLog.UserID = field.NewUint(tableName, "user_id")
	_systemAuditLog.ActionType = field.NewString(tableName, "action_type")
	_systemAuditLog.EntityType = field.NewString(tableName, "entity_type")
	_systemAuditLog.EntityID = field.NewUint(tableName, "entity_id")
	_systemAuditLog.OldValue = field.NewField(tableName, "old_value")
	_systemAuditLog.NewValue = field.NewField(tableName, "new_value")
	_systemAuditLog.IPAddress = field.NewString(tableName, "ip_address")
	_systemAuditLog.UserAgent = field.NewString(tableName, "user_agent")
	_systemAuditLog.CreatedAt = field.NewTime(tableName, "created_at")
	_systemAuditLog.User = systemAuditLogBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.Users"),
	}

	_systemAuditLog.fillFieldMap()

	return _systemAuditLog
}

type systemAuditLog struct {
	systemAuditLogDo systemAuditLogDo

	ALL        field.Asterisk
	ID         field.Uint
	UserID     field.Uint
	ActionType field.String
	EntityType field.String
	EntityID   field.Uint
	OldValue   field.Field
	NewValue   field.Field
	IPAddress  field.String
	UserAgent  field.String
	CreatedAt  field.Time
	User       systemAuditLogBelongsToUser

	fieldMap map[string]field.Expr
}

func (s systemAuditLog) Table(newTableName string) *systemAuditLog {
	s.systemAuditLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemAuditLog) As(alias string) *systemAuditLog {
	s.systemAuditLogDo.DO = *(s.systemAuditLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemAuditLog) updateTableName(table string) *systemAuditLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.UserID = field.NewUint(table, "user_id")
	s.ActionType = field.NewString(table, "action_type")
	s.EntityType = field.NewString(table, "entity_type")
	s.EntityID = field.NewUint(table, "entity_id")
	s.OldValue = field.NewField(table, "old_value")
	s.NewValue = field.NewField(table, "new_value")
	s.IPAddress = field.NewString(table, "ip_address")
	s.UserAgent = field.NewString(table, "user_agent")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *systemAuditLog) WithContext(ctx context.Context) *systemAuditLogDo {
	return s.systemAuditLogDo.WithContext(ctx)
}

func (s systemAuditLog) TableName() string { return s.systemAuditLogDo.TableName() }

func (s systemAuditLog) Alias() string { return s.systemAuditLogDo.Alias() }

func (s systemAuditLog) Columns(cols ...field.Expr) gen.Columns {
	return s.systemAuditLogDo.Columns(cols...)
}

func (s *systemAuditLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemAuditLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["action_type"] = s.ActionType
	s.fieldMap["entity_type"] = s.EntityType
	s.fieldMap["entity_id"] = s.EntityID
	s.fieldMap["old_value"] = s.OldValue
	s.fieldMap["new_value"] = s.NewValue
	s.fieldMap["ip_address"] = s.IPAddress
	s.fieldMap["user_agent"] = s.UserAgent
	s.fieldMap["created_at"] = s.CreatedAt

}

func (s systemAuditLog) clone(db *gorm.DB) systemAuditLog {
	s.systemAuditLogDo.ReplaceConnPool(db.Statement.ConnPool)
	s.User.db = db.Session(&gorm.Session{Initialized: true})
	s.User.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s systemAuditLog) replaceDB(db *gorm.DB) systemAuditLog {
	s.systemAuditLogDo.ReplaceDB(db)
	s.User.db = db.Session(&gorm.Session{})
	return s
}

type systemAuditLogBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a systemAuditLogBelongsToUser) Where(conds ...field.Expr) *systemAuditLogBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a systemAuditLogBelongsToUser) WithContext(ctx context.Context) *systemAuditLogBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a systemAuditLogBelongsToUser) Session(session *gorm.Session) *systemAuditLogBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a systemAuditLogBelongsToUser) Model(m *model.SystemAuditLog) *systemAuditLogBelongsToUserTx {
	return &systemAuditLogBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a systemAuditLogBelongsToUser) Unscoped() *systemAuditLogBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type systemAuditLogBelongsToUserTx struct{ tx *gorm.Association }

func (a systemAuditLogBelongsToUserTx) Find() (result *model.Users, err error) {
	return result, a.tx.Find(&result)
}

func (a systemAuditLogBelongsToUserTx) Append(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a systemAuditLogBelongsToUserTx) Replace(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a systemAuditLogBelongsToUserTx) Delete(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a systemAuditLogBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a systemAuditLogBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a systemAuditLogBelongsToUserTx) Unscoped() *systemAuditLogBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type systemAuditLogDo struct{ gen.DO }

func (s systemAuditLogDo) Debug() *systemAuditLogDo {
	return s.withDO(s.DO.Debug())
}

func (s systemAuditLogDo) WithContext(ctx context.Context) *systemAuditLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemAuditLogDo) ReadDB() *systemAuditLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemAuditLogDo) WriteDB() *systemAuditLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemAuditLogDo) Session(config *gorm.Session) *systemAuditLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemAuditLogDo) Clauses(conds ...clause.Expression) *systemAuditLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemAuditLogDo) Returning(value interface{}, columns ...string) *systemAuditLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemAuditLogDo) Not(conds ...gen.Condition) *systemAuditLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemAuditLogDo) Or(conds ...gen.Condition) *systemAuditLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemAuditLogDo) Select(conds ...field.Expr) *systemAuditLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemAuditLogDo) Where(conds ...gen.Condition) *systemAuditLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemAuditLogDo) Order(conds ...field.Expr) *systemAuditLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemAuditLogDo) Distinct(cols ...field.Expr) *systemAuditLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemAuditLogDo) Omit(cols ...field.Expr) *systemAuditLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemAuditLogDo) Join(table schema.Tabler, on ...field.Expr) *systemAuditLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemAuditLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *systemAuditLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemAuditLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *systemAuditLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemAuditLogDo) Group(cols ...field.Expr) *systemAuditLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemAuditLogDo) Having(conds ...gen.Condition) *systemAuditLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemAuditLogDo) Limit(limit int) *systemAuditLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemAuditLogDo) Offset(offset int) *systemAuditLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemAuditLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *systemAuditLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemAuditLogDo) Unscoped() *systemAuditLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemAuditLogDo) Create(values ...*model.SystemAuditLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemAuditLogDo) CreateInBatches(values []*model.SystemAuditLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemAuditLogDo) Save(values ...*model.SystemAuditLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemAuditLogDo) First() (*model.SystemAuditLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemAuditLog), nil
	}
}

func (s systemAuditLogDo) Take() (*model.SystemAuditLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemAuditLog), nil
	}
}

func (s systemAuditLogDo) Last() (*model.SystemAuditLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemAuditLog), nil
	}
}

func (s systemAuditLogDo) Find() ([]*model.SystemAuditLog, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemAuditLog), err
}

func (s systemAuditLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemAuditLog, err error) {
	buf := make([]*model.SystemAuditLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemAuditLogDo) FindInBatches(result *[]*model.SystemAuditLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemAuditLogDo) Attrs(attrs ...field.AssignExpr) *systemAuditLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemAuditLogDo) Assign(attrs ...field.AssignExpr) *systemAuditLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemAuditLogDo) Joins(fields ...field.RelationField) *systemAuditLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemAuditLogDo) Preload(fields ...field.RelationField) *systemAuditLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemAuditLogDo) FirstOrInit() (*model.SystemAuditLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemAuditLog), nil
	}
}

func (s systemAuditLogDo) FirstOrCreate() (*model.SystemAuditLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemAuditLog), nil
	}
}

func (s systemAuditLogDo) FindByPage(offset int, limit int) (result []*model.SystemAuditLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemAuditLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemAuditLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemAuditLogDo) Delete(models ...*model.SystemAuditLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemAuditLogDo) withDO(do gen.Dao) *systemAuditLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
