// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newUserDataRequests(db *gorm.DB, opts ...gen.DOOption) userDataRequests {
	_userDataRequests := userDataRequests{}

	_userDataRequests.userDataRequestsDo.UseDB(db, opts...)
	_userDataRequests.userDataRequestsDo.UseModel(&model.UserDataRequests{})

	tableName := _userDataRequests.userDataRequestsDo.TableName()
	_userDataRequests.ALL = field.NewAsterisk(tableName)
	_userDataRequests.ID = field.NewUint(tableName, "id")
	_userDataRequests.UserID = field.NewUint(tableName, "user_id")
	_userDataRequests.RequestType = field.NewString(tableName, "request_type")
	_userDataRequests.Status = field.NewString(tableName, "status")
	_userDataRequests.RequestedTables = field.NewString(tableName, "requested_tables")
	_userDataRequests.DateRangeStart = field.NewTime(tableName, "date_range_start")
	_userDataRequests.DateRangeEnd = field.NewTime(tableName, "date_range_end")
	_userDataRequests.RequestedAt = field.NewTime(tableName, "requested_at")
	_userDataRequests.ProcessingStartedAt = field.NewTime(tableName, "processing_started_at")
	_userDataRequests.ProcessedAt = field.NewTime(tableName, "processed_at")
	_userDataRequests.ProcessedByID = field.NewUint(tableName, "processed_by_id")
	_userDataRequests.ExportFormat = field.NewString(tableName, "export_format")
	_userDataRequests.ExportFileURL = field.NewString(tableName, "export_file_url")
	_userDataRequests.ExportExpiresAt = field.NewTime(tableName, "export_expires_at")
	_userDataRequests.DeletionReason = field.NewString(tableName, "deletion_reason")
	_userDataRequests.BackupCreated = field.NewBool(tableName, "backup_created")
	_userDataRequests.BackupLocation = field.NewString(tableName, "backup_location")
	_userDataRequests.Notes = field.NewString(tableName, "notes")
	_userDataRequests.ErrorMessage = field.NewString(tableName, "error_message")
	_userDataRequests.CreatedAt = field.NewTime(tableName, "created_at")
	_userDataRequests.User = userDataRequestsBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.Users"),
	}

	_userDataRequests.ProcessedBy = userDataRequestsBelongsToProcessedBy{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ProcessedBy", "model.Users"),
	}

	_userDataRequests.fillFieldMap()

	return _userDataRequests
}

type userDataRequests struct {
	userDataRequestsDo userDataRequestsDo

	ALL                 field.Asterisk
	ID                  field.Uint
	UserID              field.Uint
	RequestType         field.String
	Status              field.String
	RequestedTables     field.String
	DateRangeStart      field.Time
	DateRangeEnd        field.Time
	RequestedAt         field.Time
	ProcessingStartedAt field.Time
	ProcessedAt         field.Time
	ProcessedByID       field.Uint
	ExportFormat        field.String
	ExportFileURL       field.String
	ExportExpiresAt     field.Time
	DeletionReason      field.String
	BackupCreated       field.Bool
	BackupLocation      field.String
	Notes               field.String
	ErrorMessage        field.String
	CreatedAt           field.Time
	User                userDataRequestsBelongsToUser

	ProcessedBy userDataRequestsBelongsToProcessedBy

	fieldMap map[string]field.Expr
}

func (u userDataRequests) Table(newTableName string) *userDataRequests {
	u.userDataRequestsDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userDataRequests) As(alias string) *userDataRequests {
	u.userDataRequestsDo.DO = *(u.userDataRequestsDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userDataRequests) updateTableName(table string) *userDataRequests {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint(table, "id")
	u.UserID = field.NewUint(table, "user_id")
	u.RequestType = field.NewString(table, "request_type")
	u.Status = field.NewString(table, "status")
	u.RequestedTables = field.NewString(table, "requested_tables")
	u.DateRangeStart = field.NewTime(table, "date_range_start")
	u.DateRangeEnd = field.NewTime(table, "date_range_end")
	u.RequestedAt = field.NewTime(table, "requested_at")
	u.ProcessingStartedAt = field.NewTime(table, "processing_started_at")
	u.ProcessedAt = field.NewTime(table, "processed_at")
	u.ProcessedByID = field.NewUint(table, "processed_by_id")
	u.ExportFormat = field.NewString(table, "export_format")
	u.ExportFileURL = field.NewString(table, "export_file_url")
	u.ExportExpiresAt = field.NewTime(table, "export_expires_at")
	u.DeletionReason = field.NewString(table, "deletion_reason")
	u.BackupCreated = field.NewBool(table, "backup_created")
	u.BackupLocation = field.NewString(table, "backup_location")
	u.Notes = field.NewString(table, "notes")
	u.ErrorMessage = field.NewString(table, "error_message")
	u.CreatedAt = field.NewTime(table, "created_at")

	u.fillFieldMap()

	return u
}

func (u *userDataRequests) WithContext(ctx context.Context) *userDataRequestsDo {
	return u.userDataRequestsDo.WithContext(ctx)
}

func (u userDataRequests) TableName() string { return u.userDataRequestsDo.TableName() }

func (u userDataRequests) Alias() string { return u.userDataRequestsDo.Alias() }

func (u userDataRequests) Columns(cols ...field.Expr) gen.Columns {
	return u.userDataRequestsDo.Columns(cols...)
}

func (u *userDataRequests) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userDataRequests) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 22)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["request_type"] = u.RequestType
	u.fieldMap["status"] = u.Status
	u.fieldMap["requested_tables"] = u.RequestedTables
	u.fieldMap["date_range_start"] = u.DateRangeStart
	u.fieldMap["date_range_end"] = u.DateRangeEnd
	u.fieldMap["requested_at"] = u.RequestedAt
	u.fieldMap["processing_started_at"] = u.ProcessingStartedAt
	u.fieldMap["processed_at"] = u.ProcessedAt
	u.fieldMap["processed_by_id"] = u.ProcessedByID
	u.fieldMap["export_format"] = u.ExportFormat
	u.fieldMap["export_file_url"] = u.ExportFileURL
	u.fieldMap["export_expires_at"] = u.ExportExpiresAt
	u.fieldMap["deletion_reason"] = u.DeletionReason
	u.fieldMap["backup_created"] = u.BackupCreated
	u.fieldMap["backup_location"] = u.BackupLocation
	u.fieldMap["notes"] = u.Notes
	u.fieldMap["error_message"] = u.ErrorMessage
	u.fieldMap["created_at"] = u.CreatedAt

}

func (u userDataRequests) clone(db *gorm.DB) userDataRequests {
	u.userDataRequestsDo.ReplaceConnPool(db.Statement.ConnPool)
	u.User.db = db.Session(&gorm.Session{Initialized: true})
	u.User.db.Statement.ConnPool = db.Statement.ConnPool
	u.ProcessedBy.db = db.Session(&gorm.Session{Initialized: true})
	u.ProcessedBy.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u userDataRequests) replaceDB(db *gorm.DB) userDataRequests {
	u.userDataRequestsDo.ReplaceDB(db)
	u.User.db = db.Session(&gorm.Session{})
	u.ProcessedBy.db = db.Session(&gorm.Session{})
	return u
}

type userDataRequestsBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a userDataRequestsBelongsToUser) Where(conds ...field.Expr) *userDataRequestsBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userDataRequestsBelongsToUser) WithContext(ctx context.Context) *userDataRequestsBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userDataRequestsBelongsToUser) Session(session *gorm.Session) *userDataRequestsBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a userDataRequestsBelongsToUser) Model(m *model.UserDataRequests) *userDataRequestsBelongsToUserTx {
	return &userDataRequestsBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a userDataRequestsBelongsToUser) Unscoped() *userDataRequestsBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type userDataRequestsBelongsToUserTx struct{ tx *gorm.Association }

func (a userDataRequestsBelongsToUserTx) Find() (result *model.Users, err error) {
	return result, a.tx.Find(&result)
}

func (a userDataRequestsBelongsToUserTx) Append(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userDataRequestsBelongsToUserTx) Replace(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userDataRequestsBelongsToUserTx) Delete(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userDataRequestsBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a userDataRequestsBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a userDataRequestsBelongsToUserTx) Unscoped() *userDataRequestsBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userDataRequestsBelongsToProcessedBy struct {
	db *gorm.DB

	field.RelationField
}

func (a userDataRequestsBelongsToProcessedBy) Where(conds ...field.Expr) *userDataRequestsBelongsToProcessedBy {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userDataRequestsBelongsToProcessedBy) WithContext(ctx context.Context) *userDataRequestsBelongsToProcessedBy {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userDataRequestsBelongsToProcessedBy) Session(session *gorm.Session) *userDataRequestsBelongsToProcessedBy {
	a.db = a.db.Session(session)
	return &a
}

func (a userDataRequestsBelongsToProcessedBy) Model(m *model.UserDataRequests) *userDataRequestsBelongsToProcessedByTx {
	return &userDataRequestsBelongsToProcessedByTx{a.db.Model(m).Association(a.Name())}
}

func (a userDataRequestsBelongsToProcessedBy) Unscoped() *userDataRequestsBelongsToProcessedBy {
	a.db = a.db.Unscoped()
	return &a
}

type userDataRequestsBelongsToProcessedByTx struct{ tx *gorm.Association }

func (a userDataRequestsBelongsToProcessedByTx) Find() (result *model.Users, err error) {
	return result, a.tx.Find(&result)
}

func (a userDataRequestsBelongsToProcessedByTx) Append(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userDataRequestsBelongsToProcessedByTx) Replace(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userDataRequestsBelongsToProcessedByTx) Delete(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userDataRequestsBelongsToProcessedByTx) Clear() error {
	return a.tx.Clear()
}

func (a userDataRequestsBelongsToProcessedByTx) Count() int64 {
	return a.tx.Count()
}

func (a userDataRequestsBelongsToProcessedByTx) Unscoped() *userDataRequestsBelongsToProcessedByTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userDataRequestsDo struct{ gen.DO }

func (u userDataRequestsDo) Debug() *userDataRequestsDo {
	return u.withDO(u.DO.Debug())
}

func (u userDataRequestsDo) WithContext(ctx context.Context) *userDataRequestsDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userDataRequestsDo) ReadDB() *userDataRequestsDo {
	return u.Clauses(dbresolver.Read)
}

func (u userDataRequestsDo) WriteDB() *userDataRequestsDo {
	return u.Clauses(dbresolver.Write)
}

func (u userDataRequestsDo) Session(config *gorm.Session) *userDataRequestsDo {
	return u.withDO(u.DO.Session(config))
}

func (u userDataRequestsDo) Clauses(conds ...clause.Expression) *userDataRequestsDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userDataRequestsDo) Returning(value interface{}, columns ...string) *userDataRequestsDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userDataRequestsDo) Not(conds ...gen.Condition) *userDataRequestsDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userDataRequestsDo) Or(conds ...gen.Condition) *userDataRequestsDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userDataRequestsDo) Select(conds ...field.Expr) *userDataRequestsDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userDataRequestsDo) Where(conds ...gen.Condition) *userDataRequestsDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userDataRequestsDo) Order(conds ...field.Expr) *userDataRequestsDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userDataRequestsDo) Distinct(cols ...field.Expr) *userDataRequestsDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userDataRequestsDo) Omit(cols ...field.Expr) *userDataRequestsDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userDataRequestsDo) Join(table schema.Tabler, on ...field.Expr) *userDataRequestsDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userDataRequestsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userDataRequestsDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userDataRequestsDo) RightJoin(table schema.Tabler, on ...field.Expr) *userDataRequestsDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userDataRequestsDo) Group(cols ...field.Expr) *userDataRequestsDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userDataRequestsDo) Having(conds ...gen.Condition) *userDataRequestsDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userDataRequestsDo) Limit(limit int) *userDataRequestsDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userDataRequestsDo) Offset(offset int) *userDataRequestsDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userDataRequestsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userDataRequestsDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userDataRequestsDo) Unscoped() *userDataRequestsDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userDataRequestsDo) Create(values ...*model.UserDataRequests) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userDataRequestsDo) CreateInBatches(values []*model.UserDataRequests, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userDataRequestsDo) Save(values ...*model.UserDataRequests) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userDataRequestsDo) First() (*model.UserDataRequests, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDataRequests), nil
	}
}

func (u userDataRequestsDo) Take() (*model.UserDataRequests, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDataRequests), nil
	}
}

func (u userDataRequestsDo) Last() (*model.UserDataRequests, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDataRequests), nil
	}
}

func (u userDataRequestsDo) Find() ([]*model.UserDataRequests, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserDataRequests), err
}

func (u userDataRequestsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserDataRequests, err error) {
	buf := make([]*model.UserDataRequests, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userDataRequestsDo) FindInBatches(result *[]*model.UserDataRequests, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userDataRequestsDo) Attrs(attrs ...field.AssignExpr) *userDataRequestsDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userDataRequestsDo) Assign(attrs ...field.AssignExpr) *userDataRequestsDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userDataRequestsDo) Joins(fields ...field.RelationField) *userDataRequestsDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userDataRequestsDo) Preload(fields ...field.RelationField) *userDataRequestsDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userDataRequestsDo) FirstOrInit() (*model.UserDataRequests, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDataRequests), nil
	}
}

func (u userDataRequestsDo) FirstOrCreate() (*model.UserDataRequests, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDataRequests), nil
	}
}

func (u userDataRequestsDo) FindByPage(offset int, limit int) (result []*model.UserDataRequests, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userDataRequestsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userDataRequestsDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userDataRequestsDo) Delete(models ...*model.UserDataRequests) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userDataRequestsDo) withDO(do gen.Dao) *userDataRequestsDo {
	u.DO = *do.(*gen.DO)
	return u
}
