// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newPlutchikEmotions(db *gorm.DB, opts ...gen.DOOption) plutchikEmotions {
	_plutchikEmotions := plutchikEmotions{}

	_plutchikEmotions.plutchikEmotionsDo.UseDB(db, opts...)
	_plutchikEmotions.plutchikEmotionsDo.UseModel(&model.PlutchikEmotions{})

	tableName := _plutchikEmotions.plutchikEmotionsDo.TableName()
	_plutchikEmotions.ALL = field.NewAsterisk(tableName)
	_plutchikEmotions.ID = field.NewInt(tableName, "id")
	_plutchikEmotions.NameEn = field.NewString(tableName, "name_en")
	_plutchikEmotions.NameMn = field.NewString(tableName, "name_mn")
	_plutchikEmotions.OppositeEmotionID = field.NewInt(tableName, "opposite_emotion_id")
	_plutchikEmotions.IntensityLevel = field.NewInt(tableName, "intensity_level")
	_plutchikEmotions.BaseEmotionID = field.NewInt(tableName, "base_emotion_id")
	_plutchikEmotions.Color = field.NewString(tableName, "color")
	_plutchikEmotions.Emoji = field.NewString(tableName, "emoji")
	_plutchikEmotions.CreatedAt = field.NewTime(tableName, "created_at")

	_plutchikEmotions.fillFieldMap()

	return _plutchikEmotions
}

type plutchikEmotions struct {
	plutchikEmotionsDo plutchikEmotionsDo

	ALL               field.Asterisk
	ID                field.Int
	NameEn            field.String
	NameMn            field.String
	OppositeEmotionID field.Int
	IntensityLevel    field.Int
	BaseEmotionID     field.Int
	Color             field.String
	Emoji             field.String
	CreatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (p plutchikEmotions) Table(newTableName string) *plutchikEmotions {
	p.plutchikEmotionsDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p plutchikEmotions) As(alias string) *plutchikEmotions {
	p.plutchikEmotionsDo.DO = *(p.plutchikEmotionsDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *plutchikEmotions) updateTableName(table string) *plutchikEmotions {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt(table, "id")
	p.NameEn = field.NewString(table, "name_en")
	p.NameMn = field.NewString(table, "name_mn")
	p.OppositeEmotionID = field.NewInt(table, "opposite_emotion_id")
	p.IntensityLevel = field.NewInt(table, "intensity_level")
	p.BaseEmotionID = field.NewInt(table, "base_emotion_id")
	p.Color = field.NewString(table, "color")
	p.Emoji = field.NewString(table, "emoji")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *plutchikEmotions) WithContext(ctx context.Context) *plutchikEmotionsDo {
	return p.plutchikEmotionsDo.WithContext(ctx)
}

func (p plutchikEmotions) TableName() string { return p.plutchikEmotionsDo.TableName() }

func (p plutchikEmotions) Alias() string { return p.plutchikEmotionsDo.Alias() }

func (p plutchikEmotions) Columns(cols ...field.Expr) gen.Columns {
	return p.plutchikEmotionsDo.Columns(cols...)
}

func (p *plutchikEmotions) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *plutchikEmotions) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name_en"] = p.NameEn
	p.fieldMap["name_mn"] = p.NameMn
	p.fieldMap["opposite_emotion_id"] = p.OppositeEmotionID
	p.fieldMap["intensity_level"] = p.IntensityLevel
	p.fieldMap["base_emotion_id"] = p.BaseEmotionID
	p.fieldMap["color"] = p.Color
	p.fieldMap["emoji"] = p.Emoji
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p plutchikEmotions) clone(db *gorm.DB) plutchikEmotions {
	p.plutchikEmotionsDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p plutchikEmotions) replaceDB(db *gorm.DB) plutchikEmotions {
	p.plutchikEmotionsDo.ReplaceDB(db)
	return p
}

type plutchikEmotionsDo struct{ gen.DO }

func (p plutchikEmotionsDo) Debug() *plutchikEmotionsDo {
	return p.withDO(p.DO.Debug())
}

func (p plutchikEmotionsDo) WithContext(ctx context.Context) *plutchikEmotionsDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p plutchikEmotionsDo) ReadDB() *plutchikEmotionsDo {
	return p.Clauses(dbresolver.Read)
}

func (p plutchikEmotionsDo) WriteDB() *plutchikEmotionsDo {
	return p.Clauses(dbresolver.Write)
}

func (p plutchikEmotionsDo) Session(config *gorm.Session) *plutchikEmotionsDo {
	return p.withDO(p.DO.Session(config))
}

func (p plutchikEmotionsDo) Clauses(conds ...clause.Expression) *plutchikEmotionsDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p plutchikEmotionsDo) Returning(value interface{}, columns ...string) *plutchikEmotionsDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p plutchikEmotionsDo) Not(conds ...gen.Condition) *plutchikEmotionsDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p plutchikEmotionsDo) Or(conds ...gen.Condition) *plutchikEmotionsDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p plutchikEmotionsDo) Select(conds ...field.Expr) *plutchikEmotionsDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p plutchikEmotionsDo) Where(conds ...gen.Condition) *plutchikEmotionsDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p plutchikEmotionsDo) Order(conds ...field.Expr) *plutchikEmotionsDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p plutchikEmotionsDo) Distinct(cols ...field.Expr) *plutchikEmotionsDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p plutchikEmotionsDo) Omit(cols ...field.Expr) *plutchikEmotionsDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p plutchikEmotionsDo) Join(table schema.Tabler, on ...field.Expr) *plutchikEmotionsDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p plutchikEmotionsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *plutchikEmotionsDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p plutchikEmotionsDo) RightJoin(table schema.Tabler, on ...field.Expr) *plutchikEmotionsDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p plutchikEmotionsDo) Group(cols ...field.Expr) *plutchikEmotionsDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p plutchikEmotionsDo) Having(conds ...gen.Condition) *plutchikEmotionsDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p plutchikEmotionsDo) Limit(limit int) *plutchikEmotionsDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p plutchikEmotionsDo) Offset(offset int) *plutchikEmotionsDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p plutchikEmotionsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *plutchikEmotionsDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p plutchikEmotionsDo) Unscoped() *plutchikEmotionsDo {
	return p.withDO(p.DO.Unscoped())
}

func (p plutchikEmotionsDo) Create(values ...*model.PlutchikEmotions) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p plutchikEmotionsDo) CreateInBatches(values []*model.PlutchikEmotions, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p plutchikEmotionsDo) Save(values ...*model.PlutchikEmotions) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p plutchikEmotionsDo) First() (*model.PlutchikEmotions, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlutchikEmotions), nil
	}
}

func (p plutchikEmotionsDo) Take() (*model.PlutchikEmotions, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlutchikEmotions), nil
	}
}

func (p plutchikEmotionsDo) Last() (*model.PlutchikEmotions, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlutchikEmotions), nil
	}
}

func (p plutchikEmotionsDo) Find() ([]*model.PlutchikEmotions, error) {
	result, err := p.DO.Find()
	return result.([]*model.PlutchikEmotions), err
}

func (p plutchikEmotionsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlutchikEmotions, err error) {
	buf := make([]*model.PlutchikEmotions, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p plutchikEmotionsDo) FindInBatches(result *[]*model.PlutchikEmotions, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p plutchikEmotionsDo) Attrs(attrs ...field.AssignExpr) *plutchikEmotionsDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p plutchikEmotionsDo) Assign(attrs ...field.AssignExpr) *plutchikEmotionsDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p plutchikEmotionsDo) Joins(fields ...field.RelationField) *plutchikEmotionsDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p plutchikEmotionsDo) Preload(fields ...field.RelationField) *plutchikEmotionsDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p plutchikEmotionsDo) FirstOrInit() (*model.PlutchikEmotions, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlutchikEmotions), nil
	}
}

func (p plutchikEmotionsDo) FirstOrCreate() (*model.PlutchikEmotions, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlutchikEmotions), nil
	}
}

func (p plutchikEmotionsDo) FindByPage(offset int, limit int) (result []*model.PlutchikEmotions, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p plutchikEmotionsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p plutchikEmotionsDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p plutchikEmotionsDo) Delete(models ...*model.PlutchikEmotions) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *plutchikEmotionsDo) withDO(do gen.Dao) *plutchikEmotionsDo {
	p.DO = *do.(*gen.DO)
	return p
}
