// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newMoodCategories(db *gorm.DB, opts ...gen.DOOption) moodCategories {
	_moodCategories := moodCategories{}

	_moodCategories.moodCategoriesDo.UseDB(db, opts...)
	_moodCategories.moodCategoriesDo.UseModel(&model.MoodCategories{})

	tableName := _moodCategories.moodCategoriesDo.TableName()
	_moodCategories.ALL = field.NewAsterisk(tableName)
	_moodCategories.ID = field.NewInt(tableName, "id")
	_moodCategories.NameEn = field.NewString(tableName, "name_en")
	_moodCategories.NameMn = field.NewString(tableName, "name_mn")
	_moodCategories.Color = field.NewString(tableName, "color")
	_moodCategories.Icon = field.NewString(tableName, "icon")
	_moodCategories.SortOrder = field.NewInt(tableName, "sort_order")
	_moodCategories.CreatedAt = field.NewTime(tableName, "created_at")

	_moodCategories.fillFieldMap()

	return _moodCategories
}

type moodCategories struct {
	moodCategoriesDo moodCategoriesDo

	ALL       field.Asterisk
	ID        field.Int
	NameEn    field.String
	NameMn    field.String
	Color     field.String
	Icon      field.String
	SortOrder field.Int
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (m moodCategories) Table(newTableName string) *moodCategories {
	m.moodCategoriesDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m moodCategories) As(alias string) *moodCategories {
	m.moodCategoriesDo.DO = *(m.moodCategoriesDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *moodCategories) updateTableName(table string) *moodCategories {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt(table, "id")
	m.NameEn = field.NewString(table, "name_en")
	m.NameMn = field.NewString(table, "name_mn")
	m.Color = field.NewString(table, "color")
	m.Icon = field.NewString(table, "icon")
	m.SortOrder = field.NewInt(table, "sort_order")
	m.CreatedAt = field.NewTime(table, "created_at")

	m.fillFieldMap()

	return m
}

func (m *moodCategories) WithContext(ctx context.Context) *moodCategoriesDo {
	return m.moodCategoriesDo.WithContext(ctx)
}

func (m moodCategories) TableName() string { return m.moodCategoriesDo.TableName() }

func (m moodCategories) Alias() string { return m.moodCategoriesDo.Alias() }

func (m moodCategories) Columns(cols ...field.Expr) gen.Columns {
	return m.moodCategoriesDo.Columns(cols...)
}

func (m *moodCategories) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *moodCategories) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 7)
	m.fieldMap["id"] = m.ID
	m.fieldMap["name_en"] = m.NameEn
	m.fieldMap["name_mn"] = m.NameMn
	m.fieldMap["color"] = m.Color
	m.fieldMap["icon"] = m.Icon
	m.fieldMap["sort_order"] = m.SortOrder
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m moodCategories) clone(db *gorm.DB) moodCategories {
	m.moodCategoriesDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m moodCategories) replaceDB(db *gorm.DB) moodCategories {
	m.moodCategoriesDo.ReplaceDB(db)
	return m
}

type moodCategoriesDo struct{ gen.DO }

func (m moodCategoriesDo) Debug() *moodCategoriesDo {
	return m.withDO(m.DO.Debug())
}

func (m moodCategoriesDo) WithContext(ctx context.Context) *moodCategoriesDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m moodCategoriesDo) ReadDB() *moodCategoriesDo {
	return m.Clauses(dbresolver.Read)
}

func (m moodCategoriesDo) WriteDB() *moodCategoriesDo {
	return m.Clauses(dbresolver.Write)
}

func (m moodCategoriesDo) Session(config *gorm.Session) *moodCategoriesDo {
	return m.withDO(m.DO.Session(config))
}

func (m moodCategoriesDo) Clauses(conds ...clause.Expression) *moodCategoriesDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m moodCategoriesDo) Returning(value interface{}, columns ...string) *moodCategoriesDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m moodCategoriesDo) Not(conds ...gen.Condition) *moodCategoriesDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m moodCategoriesDo) Or(conds ...gen.Condition) *moodCategoriesDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m moodCategoriesDo) Select(conds ...field.Expr) *moodCategoriesDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m moodCategoriesDo) Where(conds ...gen.Condition) *moodCategoriesDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m moodCategoriesDo) Order(conds ...field.Expr) *moodCategoriesDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m moodCategoriesDo) Distinct(cols ...field.Expr) *moodCategoriesDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m moodCategoriesDo) Omit(cols ...field.Expr) *moodCategoriesDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m moodCategoriesDo) Join(table schema.Tabler, on ...field.Expr) *moodCategoriesDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m moodCategoriesDo) LeftJoin(table schema.Tabler, on ...field.Expr) *moodCategoriesDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m moodCategoriesDo) RightJoin(table schema.Tabler, on ...field.Expr) *moodCategoriesDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m moodCategoriesDo) Group(cols ...field.Expr) *moodCategoriesDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m moodCategoriesDo) Having(conds ...gen.Condition) *moodCategoriesDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m moodCategoriesDo) Limit(limit int) *moodCategoriesDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m moodCategoriesDo) Offset(offset int) *moodCategoriesDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m moodCategoriesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *moodCategoriesDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m moodCategoriesDo) Unscoped() *moodCategoriesDo {
	return m.withDO(m.DO.Unscoped())
}

func (m moodCategoriesDo) Create(values ...*model.MoodCategories) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m moodCategoriesDo) CreateInBatches(values []*model.MoodCategories, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m moodCategoriesDo) Save(values ...*model.MoodCategories) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m moodCategoriesDo) First() (*model.MoodCategories, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MoodCategories), nil
	}
}

func (m moodCategoriesDo) Take() (*model.MoodCategories, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MoodCategories), nil
	}
}

func (m moodCategoriesDo) Last() (*model.MoodCategories, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MoodCategories), nil
	}
}

func (m moodCategoriesDo) Find() ([]*model.MoodCategories, error) {
	result, err := m.DO.Find()
	return result.([]*model.MoodCategories), err
}

func (m moodCategoriesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MoodCategories, err error) {
	buf := make([]*model.MoodCategories, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m moodCategoriesDo) FindInBatches(result *[]*model.MoodCategories, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m moodCategoriesDo) Attrs(attrs ...field.AssignExpr) *moodCategoriesDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m moodCategoriesDo) Assign(attrs ...field.AssignExpr) *moodCategoriesDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m moodCategoriesDo) Joins(fields ...field.RelationField) *moodCategoriesDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m moodCategoriesDo) Preload(fields ...field.RelationField) *moodCategoriesDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m moodCategoriesDo) FirstOrInit() (*model.MoodCategories, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MoodCategories), nil
	}
}

func (m moodCategoriesDo) FirstOrCreate() (*model.MoodCategories, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MoodCategories), nil
	}
}

func (m moodCategoriesDo) FindByPage(offset int, limit int) (result []*model.MoodCategories, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m moodCategoriesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m moodCategoriesDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m moodCategoriesDo) Delete(models ...*model.MoodCategories) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *moodCategoriesDo) withDO(do gen.Dao) *moodCategoriesDo {
	m.DO = *do.(*gen.DO)
	return m
}
