// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newPlutchikCombinations(db *gorm.DB, opts ...gen.DOOption) plutchikCombinations {
	_plutchikCombinations := plutchikCombinations{}

	_plutchikCombinations.plutchikCombinationsDo.UseDB(db, opts...)
	_plutchikCombinations.plutchikCombinationsDo.UseModel(&model.PlutchikCombinations{})

	tableName := _plutchikCombinations.plutchikCombinationsDo.TableName()
	_plutchikCombinations.ALL = field.NewAsterisk(tableName)
	_plutchikCombinations.ID = field.NewInt(tableName, "id")
	_plutchikCombinations.Emotion1ID = field.NewInt(tableName, "emotion1_id")
	_plutchikCombinations.Emotion2ID = field.NewInt(tableName, "emotion2_id")
	_plutchikCombinations.CombinedNameEn = field.NewString(tableName, "combined_name_en")
	_plutchikCombinations.CombinedNameMn = field.NewString(tableName, "combined_name_mn")
	_plutchikCombinations.CombinationType = field.NewString(tableName, "combination_type")
	_plutchikCombinations.Description = field.NewString(tableName, "description")
	_plutchikCombinations.CreatedAt = field.NewTime(tableName, "created_at")

	_plutchikCombinations.fillFieldMap()

	return _plutchikCombinations
}

type plutchikCombinations struct {
	plutchikCombinationsDo plutchikCombinationsDo

	ALL             field.Asterisk
	ID              field.Int
	Emotion1ID      field.Int
	Emotion2ID      field.Int
	CombinedNameEn  field.String
	CombinedNameMn  field.String
	CombinationType field.String
	Description     field.String
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (p plutchikCombinations) Table(newTableName string) *plutchikCombinations {
	p.plutchikCombinationsDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p plutchikCombinations) As(alias string) *plutchikCombinations {
	p.plutchikCombinationsDo.DO = *(p.plutchikCombinationsDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *plutchikCombinations) updateTableName(table string) *plutchikCombinations {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt(table, "id")
	p.Emotion1ID = field.NewInt(table, "emotion1_id")
	p.Emotion2ID = field.NewInt(table, "emotion2_id")
	p.CombinedNameEn = field.NewString(table, "combined_name_en")
	p.CombinedNameMn = field.NewString(table, "combined_name_mn")
	p.CombinationType = field.NewString(table, "combination_type")
	p.Description = field.NewString(table, "description")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *plutchikCombinations) WithContext(ctx context.Context) *plutchikCombinationsDo {
	return p.plutchikCombinationsDo.WithContext(ctx)
}

func (p plutchikCombinations) TableName() string { return p.plutchikCombinationsDo.TableName() }

func (p plutchikCombinations) Alias() string { return p.plutchikCombinationsDo.Alias() }

func (p plutchikCombinations) Columns(cols ...field.Expr) gen.Columns {
	return p.plutchikCombinationsDo.Columns(cols...)
}

func (p *plutchikCombinations) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *plutchikCombinations) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 8)
	p.fieldMap["id"] = p.ID
	p.fieldMap["emotion1_id"] = p.Emotion1ID
	p.fieldMap["emotion2_id"] = p.Emotion2ID
	p.fieldMap["combined_name_en"] = p.CombinedNameEn
	p.fieldMap["combined_name_mn"] = p.CombinedNameMn
	p.fieldMap["combination_type"] = p.CombinationType
	p.fieldMap["description"] = p.Description
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p plutchikCombinations) clone(db *gorm.DB) plutchikCombinations {
	p.plutchikCombinationsDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p plutchikCombinations) replaceDB(db *gorm.DB) plutchikCombinations {
	p.plutchikCombinationsDo.ReplaceDB(db)
	return p
}

type plutchikCombinationsDo struct{ gen.DO }

func (p plutchikCombinationsDo) Debug() *plutchikCombinationsDo {
	return p.withDO(p.DO.Debug())
}

func (p plutchikCombinationsDo) WithContext(ctx context.Context) *plutchikCombinationsDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p plutchikCombinationsDo) ReadDB() *plutchikCombinationsDo {
	return p.Clauses(dbresolver.Read)
}

func (p plutchikCombinationsDo) WriteDB() *plutchikCombinationsDo {
	return p.Clauses(dbresolver.Write)
}

func (p plutchikCombinationsDo) Session(config *gorm.Session) *plutchikCombinationsDo {
	return p.withDO(p.DO.Session(config))
}

func (p plutchikCombinationsDo) Clauses(conds ...clause.Expression) *plutchikCombinationsDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p plutchikCombinationsDo) Returning(value interface{}, columns ...string) *plutchikCombinationsDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p plutchikCombinationsDo) Not(conds ...gen.Condition) *plutchikCombinationsDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p plutchikCombinationsDo) Or(conds ...gen.Condition) *plutchikCombinationsDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p plutchikCombinationsDo) Select(conds ...field.Expr) *plutchikCombinationsDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p plutchikCombinationsDo) Where(conds ...gen.Condition) *plutchikCombinationsDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p plutchikCombinationsDo) Order(conds ...field.Expr) *plutchikCombinationsDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p plutchikCombinationsDo) Distinct(cols ...field.Expr) *plutchikCombinationsDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p plutchikCombinationsDo) Omit(cols ...field.Expr) *plutchikCombinationsDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p plutchikCombinationsDo) Join(table schema.Tabler, on ...field.Expr) *plutchikCombinationsDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p plutchikCombinationsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *plutchikCombinationsDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p plutchikCombinationsDo) RightJoin(table schema.Tabler, on ...field.Expr) *plutchikCombinationsDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p plutchikCombinationsDo) Group(cols ...field.Expr) *plutchikCombinationsDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p plutchikCombinationsDo) Having(conds ...gen.Condition) *plutchikCombinationsDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p plutchikCombinationsDo) Limit(limit int) *plutchikCombinationsDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p plutchikCombinationsDo) Offset(offset int) *plutchikCombinationsDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p plutchikCombinationsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *plutchikCombinationsDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p plutchikCombinationsDo) Unscoped() *plutchikCombinationsDo {
	return p.withDO(p.DO.Unscoped())
}

func (p plutchikCombinationsDo) Create(values ...*model.PlutchikCombinations) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p plutchikCombinationsDo) CreateInBatches(values []*model.PlutchikCombinations, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p plutchikCombinationsDo) Save(values ...*model.PlutchikCombinations) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p plutchikCombinationsDo) First() (*model.PlutchikCombinations, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlutchikCombinations), nil
	}
}

func (p plutchikCombinationsDo) Take() (*model.PlutchikCombinations, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlutchikCombinations), nil
	}
}

func (p plutchikCombinationsDo) Last() (*model.PlutchikCombinations, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlutchikCombinations), nil
	}
}

func (p plutchikCombinationsDo) Find() ([]*model.PlutchikCombinations, error) {
	result, err := p.DO.Find()
	return result.([]*model.PlutchikCombinations), err
}

func (p plutchikCombinationsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlutchikCombinations, err error) {
	buf := make([]*model.PlutchikCombinations, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p plutchikCombinationsDo) FindInBatches(result *[]*model.PlutchikCombinations, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p plutchikCombinationsDo) Attrs(attrs ...field.AssignExpr) *plutchikCombinationsDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p plutchikCombinationsDo) Assign(attrs ...field.AssignExpr) *plutchikCombinationsDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p plutchikCombinationsDo) Joins(fields ...field.RelationField) *plutchikCombinationsDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p plutchikCombinationsDo) Preload(fields ...field.RelationField) *plutchikCombinationsDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p plutchikCombinationsDo) FirstOrInit() (*model.PlutchikCombinations, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlutchikCombinations), nil
	}
}

func (p plutchikCombinationsDo) FirstOrCreate() (*model.PlutchikCombinations, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlutchikCombinations), nil
	}
}

func (p plutchikCombinationsDo) FindByPage(offset int, limit int) (result []*model.PlutchikCombinations, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p plutchikCombinationsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p plutchikCombinationsDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p plutchikCombinationsDo) Delete(models ...*model.PlutchikCombinations) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *plutchikCombinationsDo) withDO(do gen.Dao) *plutchikCombinationsDo {
	p.DO = *do.(*gen.DO)
	return p
}
