// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newSystemSettings(db *gorm.DB, opts ...gen.DOOption) systemSettings {
	_systemSettings := systemSettings{}

	_systemSettings.systemSettingsDo.UseDB(db, opts...)
	_systemSettings.systemSettingsDo.UseModel(&model.SystemSettings{})

	tableName := _systemSettings.systemSettingsDo.TableName()
	_systemSettings.ALL = field.NewAsterisk(tableName)
	_systemSettings.ID = field.NewInt(tableName, "id")
	_systemSettings.SettingKey = field.NewString(tableName, "setting_key")
	_systemSettings.SettingValue = field.NewString(tableName, "setting_value")
	_systemSettings.SettingType = field.NewString(tableName, "setting_type")
	_systemSettings.Description = field.NewString(tableName, "description")
	_systemSettings.IsPublic = field.NewBool(tableName, "is_public")
	_systemSettings.IsEditable = field.NewBool(tableName, "is_editable")
	_systemSettings.UpdatedByID = field.NewUint(tableName, "updated_by_id")
	_systemSettings.CreatedAt = field.NewTime(tableName, "created_at")
	_systemSettings.UpdatedAt = field.NewTime(tableName, "updated_at")

	_systemSettings.fillFieldMap()

	return _systemSettings
}

type systemSettings struct {
	systemSettingsDo systemSettingsDo

	ALL          field.Asterisk
	ID           field.Int
	SettingKey   field.String
	SettingValue field.String
	SettingType  field.String
	Description  field.String
	IsPublic     field.Bool
	IsEditable   field.Bool
	UpdatedByID  field.Uint
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (s systemSettings) Table(newTableName string) *systemSettings {
	s.systemSettingsDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemSettings) As(alias string) *systemSettings {
	s.systemSettingsDo.DO = *(s.systemSettingsDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemSettings) updateTableName(table string) *systemSettings {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt(table, "id")
	s.SettingKey = field.NewString(table, "setting_key")
	s.SettingValue = field.NewString(table, "setting_value")
	s.SettingType = field.NewString(table, "setting_type")
	s.Description = field.NewString(table, "description")
	s.IsPublic = field.NewBool(table, "is_public")
	s.IsEditable = field.NewBool(table, "is_editable")
	s.UpdatedByID = field.NewUint(table, "updated_by_id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *systemSettings) WithContext(ctx context.Context) *systemSettingsDo {
	return s.systemSettingsDo.WithContext(ctx)
}

func (s systemSettings) TableName() string { return s.systemSettingsDo.TableName() }

func (s systemSettings) Alias() string { return s.systemSettingsDo.Alias() }

func (s systemSettings) Columns(cols ...field.Expr) gen.Columns {
	return s.systemSettingsDo.Columns(cols...)
}

func (s *systemSettings) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemSettings) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["setting_key"] = s.SettingKey
	s.fieldMap["setting_value"] = s.SettingValue
	s.fieldMap["setting_type"] = s.SettingType
	s.fieldMap["description"] = s.Description
	s.fieldMap["is_public"] = s.IsPublic
	s.fieldMap["is_editable"] = s.IsEditable
	s.fieldMap["updated_by_id"] = s.UpdatedByID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s systemSettings) clone(db *gorm.DB) systemSettings {
	s.systemSettingsDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemSettings) replaceDB(db *gorm.DB) systemSettings {
	s.systemSettingsDo.ReplaceDB(db)
	return s
}

type systemSettingsDo struct{ gen.DO }

func (s systemSettingsDo) Debug() *systemSettingsDo {
	return s.withDO(s.DO.Debug())
}

func (s systemSettingsDo) WithContext(ctx context.Context) *systemSettingsDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemSettingsDo) ReadDB() *systemSettingsDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemSettingsDo) WriteDB() *systemSettingsDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemSettingsDo) Session(config *gorm.Session) *systemSettingsDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemSettingsDo) Clauses(conds ...clause.Expression) *systemSettingsDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemSettingsDo) Returning(value interface{}, columns ...string) *systemSettingsDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemSettingsDo) Not(conds ...gen.Condition) *systemSettingsDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemSettingsDo) Or(conds ...gen.Condition) *systemSettingsDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemSettingsDo) Select(conds ...field.Expr) *systemSettingsDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemSettingsDo) Where(conds ...gen.Condition) *systemSettingsDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemSettingsDo) Order(conds ...field.Expr) *systemSettingsDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemSettingsDo) Distinct(cols ...field.Expr) *systemSettingsDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemSettingsDo) Omit(cols ...field.Expr) *systemSettingsDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemSettingsDo) Join(table schema.Tabler, on ...field.Expr) *systemSettingsDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemSettingsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *systemSettingsDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemSettingsDo) RightJoin(table schema.Tabler, on ...field.Expr) *systemSettingsDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemSettingsDo) Group(cols ...field.Expr) *systemSettingsDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemSettingsDo) Having(conds ...gen.Condition) *systemSettingsDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemSettingsDo) Limit(limit int) *systemSettingsDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemSettingsDo) Offset(offset int) *systemSettingsDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemSettingsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *systemSettingsDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemSettingsDo) Unscoped() *systemSettingsDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemSettingsDo) Create(values ...*model.SystemSettings) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemSettingsDo) CreateInBatches(values []*model.SystemSettings, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemSettingsDo) Save(values ...*model.SystemSettings) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemSettingsDo) First() (*model.SystemSettings, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSettings), nil
	}
}

func (s systemSettingsDo) Take() (*model.SystemSettings, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSettings), nil
	}
}

func (s systemSettingsDo) Last() (*model.SystemSettings, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSettings), nil
	}
}

func (s systemSettingsDo) Find() ([]*model.SystemSettings, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemSettings), err
}

func (s systemSettingsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemSettings, err error) {
	buf := make([]*model.SystemSettings, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemSettingsDo) FindInBatches(result *[]*model.SystemSettings, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemSettingsDo) Attrs(attrs ...field.AssignExpr) *systemSettingsDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemSettingsDo) Assign(attrs ...field.AssignExpr) *systemSettingsDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemSettingsDo) Joins(fields ...field.RelationField) *systemSettingsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemSettingsDo) Preload(fields ...field.RelationField) *systemSettingsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemSettingsDo) FirstOrInit() (*model.SystemSettings, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSettings), nil
	}
}

func (s systemSettingsDo) FirstOrCreate() (*model.SystemSettings, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemSettings), nil
	}
}

func (s systemSettingsDo) FindByPage(offset int, limit int) (result []*model.SystemSettings, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemSettingsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemSettingsDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemSettingsDo) Delete(models ...*model.SystemSettings) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemSettingsDo) withDO(do gen.Dao) *systemSettingsDo {
	s.DO = *do.(*gen.DO)
	return s
}
