// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newUserSessions(db *gorm.DB, opts ...gen.DOOption) userSessions {
	_userSessions := userSessions{}

	_userSessions.userSessionsDo.UseDB(db, opts...)
	_userSessions.userSessionsDo.UseModel(&model.UserSessions{})

	tableName := _userSessions.userSessionsDo.TableName()
	_userSessions.ALL = field.NewAsterisk(tableName)
	_userSessions.ID = field.NewUint(tableName, "id")
	_userSessions.UserID = field.NewUint(tableName, "user_id")
	_userSessions.TokenHash = field.NewString(tableName, "token_hash")
	_userSessions.DeviceInfo = field.NewString(tableName, "device_info")
	_userSessions.IPAddress = field.NewString(tableName, "ip_address")
	_userSessions.UserAgent = field.NewString(tableName, "user_agent")
	_userSessions.IsActive = field.NewBool(tableName, "is_active")
	_userSessions.LastActivity = field.NewTime(tableName, "last_activity")
	_userSessions.ExpiresAt = field.NewTime(tableName, "expires_at")
	_userSessions.CreatedAt = field.NewTime(tableName, "created_at")
	_userSessions.RevokedAt = field.NewTime(tableName, "revoked_at")
	_userSessions.RevokeReason = field.NewString(tableName, "revoke_reason")
	_userSessions.User = userSessionsBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.Users"),
	}

	_userSessions.fillFieldMap()

	return _userSessions
}

type userSessions struct {
	userSessionsDo userSessionsDo

	ALL          field.Asterisk
	ID           field.Uint
	UserID       field.Uint
	TokenHash    field.String
	DeviceInfo   field.String
	IPAddress    field.String
	UserAgent    field.String
	IsActive     field.Bool
	LastActivity field.Time
	ExpiresAt    field.Time
	CreatedAt    field.Time
	RevokedAt    field.Time
	RevokeReason field.String
	User         userSessionsBelongsToUser

	fieldMap map[string]field.Expr
}

func (u userSessions) Table(newTableName string) *userSessions {
	u.userSessionsDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userSessions) As(alias string) *userSessions {
	u.userSessionsDo.DO = *(u.userSessionsDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userSessions) updateTableName(table string) *userSessions {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint(table, "id")
	u.UserID = field.NewUint(table, "user_id")
	u.TokenHash = field.NewString(table, "token_hash")
	u.DeviceInfo = field.NewString(table, "device_info")
	u.IPAddress = field.NewString(table, "ip_address")
	u.UserAgent = field.NewString(table, "user_agent")
	u.IsActive = field.NewBool(table, "is_active")
	u.LastActivity = field.NewTime(table, "last_activity")
	u.ExpiresAt = field.NewTime(table, "expires_at")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.RevokedAt = field.NewTime(table, "revoked_at")
	u.RevokeReason = field.NewString(table, "revoke_reason")

	u.fillFieldMap()

	return u
}

func (u *userSessions) WithContext(ctx context.Context) *userSessionsDo {
	return u.userSessionsDo.WithContext(ctx)
}

func (u userSessions) TableName() string { return u.userSessionsDo.TableName() }

func (u userSessions) Alias() string { return u.userSessionsDo.Alias() }

func (u userSessions) Columns(cols ...field.Expr) gen.Columns {
	return u.userSessionsDo.Columns(cols...)
}

func (u *userSessions) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userSessions) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 13)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["token_hash"] = u.TokenHash
	u.fieldMap["device_info"] = u.DeviceInfo
	u.fieldMap["ip_address"] = u.IPAddress
	u.fieldMap["user_agent"] = u.UserAgent
	u.fieldMap["is_active"] = u.IsActive
	u.fieldMap["last_activity"] = u.LastActivity
	u.fieldMap["expires_at"] = u.ExpiresAt
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["revoked_at"] = u.RevokedAt
	u.fieldMap["revoke_reason"] = u.RevokeReason

}

func (u userSessions) clone(db *gorm.DB) userSessions {
	u.userSessionsDo.ReplaceConnPool(db.Statement.ConnPool)
	u.User.db = db.Session(&gorm.Session{Initialized: true})
	u.User.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u userSessions) replaceDB(db *gorm.DB) userSessions {
	u.userSessionsDo.ReplaceDB(db)
	u.User.db = db.Session(&gorm.Session{})
	return u
}

type userSessionsBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a userSessionsBelongsToUser) Where(conds ...field.Expr) *userSessionsBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userSessionsBelongsToUser) WithContext(ctx context.Context) *userSessionsBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userSessionsBelongsToUser) Session(session *gorm.Session) *userSessionsBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a userSessionsBelongsToUser) Model(m *model.UserSessions) *userSessionsBelongsToUserTx {
	return &userSessionsBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a userSessionsBelongsToUser) Unscoped() *userSessionsBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type userSessionsBelongsToUserTx struct{ tx *gorm.Association }

func (a userSessionsBelongsToUserTx) Find() (result *model.Users, err error) {
	return result, a.tx.Find(&result)
}

func (a userSessionsBelongsToUserTx) Append(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userSessionsBelongsToUserTx) Replace(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userSessionsBelongsToUserTx) Delete(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userSessionsBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a userSessionsBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a userSessionsBelongsToUserTx) Unscoped() *userSessionsBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userSessionsDo struct{ gen.DO }

func (u userSessionsDo) Debug() *userSessionsDo {
	return u.withDO(u.DO.Debug())
}

func (u userSessionsDo) WithContext(ctx context.Context) *userSessionsDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userSessionsDo) ReadDB() *userSessionsDo {
	return u.Clauses(dbresolver.Read)
}

func (u userSessionsDo) WriteDB() *userSessionsDo {
	return u.Clauses(dbresolver.Write)
}

func (u userSessionsDo) Session(config *gorm.Session) *userSessionsDo {
	return u.withDO(u.DO.Session(config))
}

func (u userSessionsDo) Clauses(conds ...clause.Expression) *userSessionsDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userSessionsDo) Returning(value interface{}, columns ...string) *userSessionsDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userSessionsDo) Not(conds ...gen.Condition) *userSessionsDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userSessionsDo) Or(conds ...gen.Condition) *userSessionsDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userSessionsDo) Select(conds ...field.Expr) *userSessionsDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userSessionsDo) Where(conds ...gen.Condition) *userSessionsDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userSessionsDo) Order(conds ...field.Expr) *userSessionsDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userSessionsDo) Distinct(cols ...field.Expr) *userSessionsDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userSessionsDo) Omit(cols ...field.Expr) *userSessionsDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userSessionsDo) Join(table schema.Tabler, on ...field.Expr) *userSessionsDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userSessionsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userSessionsDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userSessionsDo) RightJoin(table schema.Tabler, on ...field.Expr) *userSessionsDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userSessionsDo) Group(cols ...field.Expr) *userSessionsDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userSessionsDo) Having(conds ...gen.Condition) *userSessionsDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userSessionsDo) Limit(limit int) *userSessionsDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userSessionsDo) Offset(offset int) *userSessionsDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userSessionsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userSessionsDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userSessionsDo) Unscoped() *userSessionsDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userSessionsDo) Create(values ...*model.UserSessions) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userSessionsDo) CreateInBatches(values []*model.UserSessions, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userSessionsDo) Save(values ...*model.UserSessions) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userSessionsDo) First() (*model.UserSessions, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserSessions), nil
	}
}

func (u userSessionsDo) Take() (*model.UserSessions, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserSessions), nil
	}
}

func (u userSessionsDo) Last() (*model.UserSessions, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserSessions), nil
	}
}

func (u userSessionsDo) Find() ([]*model.UserSessions, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserSessions), err
}

func (u userSessionsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserSessions, err error) {
	buf := make([]*model.UserSessions, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userSessionsDo) FindInBatches(result *[]*model.UserSessions, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userSessionsDo) Attrs(attrs ...field.AssignExpr) *userSessionsDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userSessionsDo) Assign(attrs ...field.AssignExpr) *userSessionsDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userSessionsDo) Joins(fields ...field.RelationField) *userSessionsDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userSessionsDo) Preload(fields ...field.RelationField) *userSessionsDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userSessionsDo) FirstOrInit() (*model.UserSessions, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserSessions), nil
	}
}

func (u userSessionsDo) FirstOrCreate() (*model.UserSessions, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserSessions), nil
	}
}

func (u userSessionsDo) FindByPage(offset int, limit int) (result []*model.UserSessions, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userSessionsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userSessionsDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userSessionsDo) Delete(models ...*model.UserSessions) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userSessionsDo) withDO(do gen.Dao) *userSessionsDo {
	u.DO = *do.(*gen.DO)
	return u
}
