// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newRoleOwners(db *gorm.DB, opts ...gen.DOOption) roleOwners {
	_roleOwners := roleOwners{}

	_roleOwners.roleOwnersDo.UseDB(db, opts...)
	_roleOwners.roleOwnersDo.UseModel(&model.RoleOwners{})

	tableName := _roleOwners.roleOwnersDo.TableName()
	_roleOwners.ALL = field.NewAsterisk(tableName)
	_roleOwners.ID = field.NewUint(tableName, "id")
	_roleOwners.RoleID = field.NewUint(tableName, "role_id")
	_roleOwners.OwnerID = field.NewUint(tableName, "owner_id")
	_roleOwners.Status = field.NewString(tableName, "status")
	_roleOwners.AssignedByID = field.NewUint(tableName, "assigned_by_id")
	_roleOwners.CreatedAt = field.NewTime(tableName, "created_at")
	_roleOwners.RevokedAt = field.NewTime(tableName, "revoked_at")

	_roleOwners.fillFieldMap()

	return _roleOwners
}

type roleOwners struct {
	roleOwnersDo roleOwnersDo

	ALL          field.Asterisk
	ID           field.Uint
	RoleID       field.Uint
	OwnerID      field.Uint
	Status       field.String
	AssignedByID field.Uint
	CreatedAt    field.Time
	RevokedAt    field.Time

	fieldMap map[string]field.Expr
}

func (r roleOwners) Table(newTableName string) *roleOwners {
	r.roleOwnersDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roleOwners) As(alias string) *roleOwners {
	r.roleOwnersDo.DO = *(r.roleOwnersDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roleOwners) updateTableName(table string) *roleOwners {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint(table, "id")
	r.RoleID = field.NewUint(table, "role_id")
	r.OwnerID = field.NewUint(table, "owner_id")
	r.Status = field.NewString(table, "status")
	r.AssignedByID = field.NewUint(table, "assigned_by_id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.RevokedAt = field.NewTime(table, "revoked_at")

	r.fillFieldMap()

	return r
}

func (r *roleOwners) WithContext(ctx context.Context) *roleOwnersDo {
	return r.roleOwnersDo.WithContext(ctx)
}

func (r roleOwners) TableName() string { return r.roleOwnersDo.TableName() }

func (r roleOwners) Alias() string { return r.roleOwnersDo.Alias() }

func (r roleOwners) Columns(cols ...field.Expr) gen.Columns { return r.roleOwnersDo.Columns(cols...) }

func (r *roleOwners) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roleOwners) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["role_id"] = r.RoleID
	r.fieldMap["owner_id"] = r.OwnerID
	r.fieldMap["status"] = r.Status
	r.fieldMap["assigned_by_id"] = r.AssignedByID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["revoked_at"] = r.RevokedAt
}

func (r roleOwners) clone(db *gorm.DB) roleOwners {
	r.roleOwnersDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roleOwners) replaceDB(db *gorm.DB) roleOwners {
	r.roleOwnersDo.ReplaceDB(db)
	return r
}

type roleOwnersDo struct{ gen.DO }

func (r roleOwnersDo) Debug() *roleOwnersDo {
	return r.withDO(r.DO.Debug())
}

func (r roleOwnersDo) WithContext(ctx context.Context) *roleOwnersDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roleOwnersDo) ReadDB() *roleOwnersDo {
	return r.Clauses(dbresolver.Read)
}

func (r roleOwnersDo) WriteDB() *roleOwnersDo {
	return r.Clauses(dbresolver.Write)
}

func (r roleOwnersDo) Session(config *gorm.Session) *roleOwnersDo {
	return r.withDO(r.DO.Session(config))
}

func (r roleOwnersDo) Clauses(conds ...clause.Expression) *roleOwnersDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roleOwnersDo) Returning(value interface{}, columns ...string) *roleOwnersDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roleOwnersDo) Not(conds ...gen.Condition) *roleOwnersDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roleOwnersDo) Or(conds ...gen.Condition) *roleOwnersDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roleOwnersDo) Select(conds ...field.Expr) *roleOwnersDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roleOwnersDo) Where(conds ...gen.Condition) *roleOwnersDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roleOwnersDo) Order(conds ...field.Expr) *roleOwnersDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roleOwnersDo) Distinct(cols ...field.Expr) *roleOwnersDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roleOwnersDo) Omit(cols ...field.Expr) *roleOwnersDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roleOwnersDo) Join(table schema.Tabler, on ...field.Expr) *roleOwnersDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roleOwnersDo) LeftJoin(table schema.Tabler, on ...field.Expr) *roleOwnersDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roleOwnersDo) RightJoin(table schema.Tabler, on ...field.Expr) *roleOwnersDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roleOwnersDo) Group(cols ...field.Expr) *roleOwnersDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roleOwnersDo) Having(conds ...gen.Condition) *roleOwnersDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roleOwnersDo) Limit(limit int) *roleOwnersDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roleOwnersDo) Offset(offset int) *roleOwnersDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roleOwnersDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *roleOwnersDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roleOwnersDo) Unscoped() *roleOwnersDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roleOwnersDo) Create(values ...*model.RoleOwners) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roleOwnersDo) CreateInBatches(values []*model.RoleOwners, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roleOwnersDo) Save(values ...*model.RoleOwners) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roleOwnersDo) First() (*model.RoleOwners, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleOwners), nil
	}
}

func (r roleOwnersDo) Take() (*model.RoleOwners, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleOwners), nil
	}
}

func (r roleOwnersDo) Last() (*model.RoleOwners, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleOwners), nil
	}
}

func (r roleOwnersDo) Find() ([]*model.RoleOwners, error) {
	result, err := r.DO.Find()
	return result.([]*model.RoleOwners), err
}

func (r roleOwnersDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoleOwners, err error) {
	buf := make([]*model.RoleOwners, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roleOwnersDo) FindInBatches(result *[]*model.RoleOwners, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roleOwnersDo) Attrs(attrs ...field.AssignExpr) *roleOwnersDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roleOwnersDo) Assign(attrs ...field.AssignExpr) *roleOwnersDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roleOwnersDo) Joins(fields ...field.RelationField) *roleOwnersDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roleOwnersDo) Preload(fields ...field.RelationField) *roleOwnersDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roleOwnersDo) FirstOrInit() (*model.RoleOwners, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleOwners), nil
	}
}

func (r roleOwnersDo) FirstOrCreate() (*model.RoleOwners, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleOwners), nil
	}
}

func (r roleOwnersDo) FindByPage(offset int, limit int) (result []*model.RoleOwners, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roleOwnersDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roleOwnersDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roleOwnersDo) Delete(models ...*model.RoleOwners) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roleOwnersDo) withDO(do gen.Dao) *roleOwnersDo {
	r.DO = *do.(*gen.DO)
	return r
}
