// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newDeletedDataLog(db *gorm.DB, opts ...gen.DOOption) deletedDataLog {
	_deletedDataLog := deletedDataLog{}

	_deletedDataLog.deletedDataLogDo.UseDB(db, opts...)
	_deletedDataLog.deletedDataLogDo.UseModel(&model.DeletedDataLog{})

	tableName := _deletedDataLog.deletedDataLogDo.TableName()
	_deletedDataLog.ALL = field.NewAsterisk(tableName)
	_deletedDataLog.ID = field.NewUint(tableName, "id")
	_deletedDataLog.UserID = field.NewUint(tableName, "user_id")
	_deletedDataLog.TableName_ = field.NewString(tableName, "table_name")
	_deletedDataLog.RecordID = field.NewUint(tableName, "record_id")
	_deletedDataLog.RecordData = field.NewField(tableName, "record_data")
	_deletedDataLog.DeletedReason = field.NewString(tableName, "deleted_reason")
	_deletedDataLog.DeletionMethod = field.NewString(tableName, "deletion_method")
	_deletedDataLog.DeletedAt = field.NewField(tableName, "deleted_at")
	_deletedDataLog.DeletedByID = field.NewUint(tableName, "deleted_by_id")
	_deletedDataLog.CanRecover = field.NewBool(tableName, "can_recover")
	_deletedDataLog.RecoveryExpiresAt = field.NewTime(tableName, "recovery_expires_at")

	_deletedDataLog.fillFieldMap()

	return _deletedDataLog
}

type deletedDataLog struct {
	deletedDataLogDo deletedDataLogDo

	ALL               field.Asterisk
	ID                field.Uint
	UserID            field.Uint
	TableName_        field.String
	RecordID          field.Uint
	RecordData        field.Field
	DeletedReason     field.String
	DeletionMethod    field.String
	DeletedAt         field.Field
	DeletedByID       field.Uint
	CanRecover        field.Bool
	RecoveryExpiresAt field.Time

	fieldMap map[string]field.Expr
}

func (d deletedDataLog) Table(newTableName string) *deletedDataLog {
	d.deletedDataLogDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deletedDataLog) As(alias string) *deletedDataLog {
	d.deletedDataLogDo.DO = *(d.deletedDataLogDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deletedDataLog) updateTableName(table string) *deletedDataLog {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint(table, "id")
	d.UserID = field.NewUint(table, "user_id")
	d.TableName_ = field.NewString(table, "table_name")
	d.RecordID = field.NewUint(table, "record_id")
	d.RecordData = field.NewField(table, "record_data")
	d.DeletedReason = field.NewString(table, "deleted_reason")
	d.DeletionMethod = field.NewString(table, "deletion_method")
	d.DeletedAt = field.NewField(table, "deleted_at")
	d.DeletedByID = field.NewUint(table, "deleted_by_id")
	d.CanRecover = field.NewBool(table, "can_recover")
	d.RecoveryExpiresAt = field.NewTime(table, "recovery_expires_at")

	d.fillFieldMap()

	return d
}

func (d *deletedDataLog) WithContext(ctx context.Context) *deletedDataLogDo {
	return d.deletedDataLogDo.WithContext(ctx)
}

func (d deletedDataLog) TableName() string { return d.deletedDataLogDo.TableName() }

func (d deletedDataLog) Alias() string { return d.deletedDataLogDo.Alias() }

func (d deletedDataLog) Columns(cols ...field.Expr) gen.Columns {
	return d.deletedDataLogDo.Columns(cols...)
}

func (d *deletedDataLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deletedDataLog) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 11)
	d.fieldMap["id"] = d.ID
	d.fieldMap["user_id"] = d.UserID
	d.fieldMap["table_name"] = d.TableName_
	d.fieldMap["record_id"] = d.RecordID
	d.fieldMap["record_data"] = d.RecordData
	d.fieldMap["deleted_reason"] = d.DeletedReason
	d.fieldMap["deletion_method"] = d.DeletionMethod
	d.fieldMap["deleted_at"] = d.DeletedAt
	d.fieldMap["deleted_by_id"] = d.DeletedByID
	d.fieldMap["can_recover"] = d.CanRecover
	d.fieldMap["recovery_expires_at"] = d.RecoveryExpiresAt
}

func (d deletedDataLog) clone(db *gorm.DB) deletedDataLog {
	d.deletedDataLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deletedDataLog) replaceDB(db *gorm.DB) deletedDataLog {
	d.deletedDataLogDo.ReplaceDB(db)
	return d
}

type deletedDataLogDo struct{ gen.DO }

func (d deletedDataLogDo) Debug() *deletedDataLogDo {
	return d.withDO(d.DO.Debug())
}

func (d deletedDataLogDo) WithContext(ctx context.Context) *deletedDataLogDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deletedDataLogDo) ReadDB() *deletedDataLogDo {
	return d.Clauses(dbresolver.Read)
}

func (d deletedDataLogDo) WriteDB() *deletedDataLogDo {
	return d.Clauses(dbresolver.Write)
}

func (d deletedDataLogDo) Session(config *gorm.Session) *deletedDataLogDo {
	return d.withDO(d.DO.Session(config))
}

func (d deletedDataLogDo) Clauses(conds ...clause.Expression) *deletedDataLogDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deletedDataLogDo) Returning(value interface{}, columns ...string) *deletedDataLogDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deletedDataLogDo) Not(conds ...gen.Condition) *deletedDataLogDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deletedDataLogDo) Or(conds ...gen.Condition) *deletedDataLogDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deletedDataLogDo) Select(conds ...field.Expr) *deletedDataLogDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deletedDataLogDo) Where(conds ...gen.Condition) *deletedDataLogDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deletedDataLogDo) Order(conds ...field.Expr) *deletedDataLogDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deletedDataLogDo) Distinct(cols ...field.Expr) *deletedDataLogDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deletedDataLogDo) Omit(cols ...field.Expr) *deletedDataLogDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deletedDataLogDo) Join(table schema.Tabler, on ...field.Expr) *deletedDataLogDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deletedDataLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *deletedDataLogDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deletedDataLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *deletedDataLogDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deletedDataLogDo) Group(cols ...field.Expr) *deletedDataLogDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deletedDataLogDo) Having(conds ...gen.Condition) *deletedDataLogDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deletedDataLogDo) Limit(limit int) *deletedDataLogDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deletedDataLogDo) Offset(offset int) *deletedDataLogDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deletedDataLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *deletedDataLogDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deletedDataLogDo) Unscoped() *deletedDataLogDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deletedDataLogDo) Create(values ...*model.DeletedDataLog) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deletedDataLogDo) CreateInBatches(values []*model.DeletedDataLog, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deletedDataLogDo) Save(values ...*model.DeletedDataLog) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deletedDataLogDo) First() (*model.DeletedDataLog, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeletedDataLog), nil
	}
}

func (d deletedDataLogDo) Take() (*model.DeletedDataLog, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeletedDataLog), nil
	}
}

func (d deletedDataLogDo) Last() (*model.DeletedDataLog, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeletedDataLog), nil
	}
}

func (d deletedDataLogDo) Find() ([]*model.DeletedDataLog, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeletedDataLog), err
}

func (d deletedDataLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeletedDataLog, err error) {
	buf := make([]*model.DeletedDataLog, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deletedDataLogDo) FindInBatches(result *[]*model.DeletedDataLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deletedDataLogDo) Attrs(attrs ...field.AssignExpr) *deletedDataLogDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deletedDataLogDo) Assign(attrs ...field.AssignExpr) *deletedDataLogDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deletedDataLogDo) Joins(fields ...field.RelationField) *deletedDataLogDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deletedDataLogDo) Preload(fields ...field.RelationField) *deletedDataLogDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deletedDataLogDo) FirstOrInit() (*model.DeletedDataLog, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeletedDataLog), nil
	}
}

func (d deletedDataLogDo) FirstOrCreate() (*model.DeletedDataLog, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeletedDataLog), nil
	}
}

func (d deletedDataLogDo) FindByPage(offset int, limit int) (result []*model.DeletedDataLog, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deletedDataLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deletedDataLogDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deletedDataLogDo) Delete(models ...*model.DeletedDataLog) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deletedDataLogDo) withDO(do gen.Dao) *deletedDataLogDo {
	d.DO = *do.(*gen.DO)
	return d
}
