// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newValueReflections(db *gorm.DB, opts ...gen.DOOption) valueReflections {
	_valueReflections := valueReflections{}

	_valueReflections.valueReflectionsDo.UseDB(db, opts...)
	_valueReflections.valueReflectionsDo.UseModel(&model.ValueReflections{})

	tableName := _valueReflections.valueReflectionsDo.TableName()
	_valueReflections.ALL = field.NewAsterisk(tableName)
	_valueReflections.ID = field.NewUint(tableName, "id")
	_valueReflections.UserID = field.NewUint(tableName, "user_id")
	_valueReflections.ValueID = field.NewUint(tableName, "value_id")
	_valueReflections.SourceType = field.NewString(tableName, "source_type")
	_valueReflections.SourceID = field.NewUint(tableName, "source_id")
	_valueReflections.ReflectionDate = field.NewTime(tableName, "reflection_date")
	_valueReflections.AlignmentScore = field.NewInt(tableName, "alignment_score")
	_valueReflections.Notes = field.NewString(tableName, "notes")
	_valueReflections.CreatedAt = field.NewTime(tableName, "created_at")
	_valueReflections.User = valueReflectionsBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.Users"),
	}

	_valueReflections.Value = valueReflectionsBelongsToValue{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Value", "model.CoreValues"),
		User: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Value.User", "model.Users"),
		},
		MaslowLevel: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Value.MaslowLevel", "model.MaslowLevels"),
		},
	}

	_valueReflections.fillFieldMap()

	return _valueReflections
}

type valueReflections struct {
	valueReflectionsDo valueReflectionsDo

	ALL            field.Asterisk
	ID             field.Uint
	UserID         field.Uint
	ValueID        field.Uint
	SourceType     field.String
	SourceID       field.Uint
	ReflectionDate field.Time
	AlignmentScore field.Int
	Notes          field.String
	CreatedAt      field.Time
	User           valueReflectionsBelongsToUser

	Value valueReflectionsBelongsToValue

	fieldMap map[string]field.Expr
}

func (v valueReflections) Table(newTableName string) *valueReflections {
	v.valueReflectionsDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v valueReflections) As(alias string) *valueReflections {
	v.valueReflectionsDo.DO = *(v.valueReflectionsDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *valueReflections) updateTableName(table string) *valueReflections {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewUint(table, "id")
	v.UserID = field.NewUint(table, "user_id")
	v.ValueID = field.NewUint(table, "value_id")
	v.SourceType = field.NewString(table, "source_type")
	v.SourceID = field.NewUint(table, "source_id")
	v.ReflectionDate = field.NewTime(table, "reflection_date")
	v.AlignmentScore = field.NewInt(table, "alignment_score")
	v.Notes = field.NewString(table, "notes")
	v.CreatedAt = field.NewTime(table, "created_at")

	v.fillFieldMap()

	return v
}

func (v *valueReflections) WithContext(ctx context.Context) *valueReflectionsDo {
	return v.valueReflectionsDo.WithContext(ctx)
}

func (v valueReflections) TableName() string { return v.valueReflectionsDo.TableName() }

func (v valueReflections) Alias() string { return v.valueReflectionsDo.Alias() }

func (v valueReflections) Columns(cols ...field.Expr) gen.Columns {
	return v.valueReflectionsDo.Columns(cols...)
}

func (v *valueReflections) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *valueReflections) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 11)
	v.fieldMap["id"] = v.ID
	v.fieldMap["user_id"] = v.UserID
	v.fieldMap["value_id"] = v.ValueID
	v.fieldMap["source_type"] = v.SourceType
	v.fieldMap["source_id"] = v.SourceID
	v.fieldMap["reflection_date"] = v.ReflectionDate
	v.fieldMap["alignment_score"] = v.AlignmentScore
	v.fieldMap["notes"] = v.Notes
	v.fieldMap["created_at"] = v.CreatedAt

}

func (v valueReflections) clone(db *gorm.DB) valueReflections {
	v.valueReflectionsDo.ReplaceConnPool(db.Statement.ConnPool)
	v.User.db = db.Session(&gorm.Session{Initialized: true})
	v.User.db.Statement.ConnPool = db.Statement.ConnPool
	v.Value.db = db.Session(&gorm.Session{Initialized: true})
	v.Value.db.Statement.ConnPool = db.Statement.ConnPool
	return v
}

func (v valueReflections) replaceDB(db *gorm.DB) valueReflections {
	v.valueReflectionsDo.ReplaceDB(db)
	v.User.db = db.Session(&gorm.Session{})
	v.Value.db = db.Session(&gorm.Session{})
	return v
}

type valueReflectionsBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a valueReflectionsBelongsToUser) Where(conds ...field.Expr) *valueReflectionsBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a valueReflectionsBelongsToUser) WithContext(ctx context.Context) *valueReflectionsBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a valueReflectionsBelongsToUser) Session(session *gorm.Session) *valueReflectionsBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a valueReflectionsBelongsToUser) Model(m *model.ValueReflections) *valueReflectionsBelongsToUserTx {
	return &valueReflectionsBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a valueReflectionsBelongsToUser) Unscoped() *valueReflectionsBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type valueReflectionsBelongsToUserTx struct{ tx *gorm.Association }

func (a valueReflectionsBelongsToUserTx) Find() (result *model.Users, err error) {
	return result, a.tx.Find(&result)
}

func (a valueReflectionsBelongsToUserTx) Append(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a valueReflectionsBelongsToUserTx) Replace(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a valueReflectionsBelongsToUserTx) Delete(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a valueReflectionsBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a valueReflectionsBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a valueReflectionsBelongsToUserTx) Unscoped() *valueReflectionsBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type valueReflectionsBelongsToValue struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
	}
	MaslowLevel struct {
		field.RelationField
	}
}

func (a valueReflectionsBelongsToValue) Where(conds ...field.Expr) *valueReflectionsBelongsToValue {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a valueReflectionsBelongsToValue) WithContext(ctx context.Context) *valueReflectionsBelongsToValue {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a valueReflectionsBelongsToValue) Session(session *gorm.Session) *valueReflectionsBelongsToValue {
	a.db = a.db.Session(session)
	return &a
}

func (a valueReflectionsBelongsToValue) Model(m *model.ValueReflections) *valueReflectionsBelongsToValueTx {
	return &valueReflectionsBelongsToValueTx{a.db.Model(m).Association(a.Name())}
}

func (a valueReflectionsBelongsToValue) Unscoped() *valueReflectionsBelongsToValue {
	a.db = a.db.Unscoped()
	return &a
}

type valueReflectionsBelongsToValueTx struct{ tx *gorm.Association }

func (a valueReflectionsBelongsToValueTx) Find() (result *model.CoreValues, err error) {
	return result, a.tx.Find(&result)
}

func (a valueReflectionsBelongsToValueTx) Append(values ...*model.CoreValues) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a valueReflectionsBelongsToValueTx) Replace(values ...*model.CoreValues) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a valueReflectionsBelongsToValueTx) Delete(values ...*model.CoreValues) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a valueReflectionsBelongsToValueTx) Clear() error {
	return a.tx.Clear()
}

func (a valueReflectionsBelongsToValueTx) Count() int64 {
	return a.tx.Count()
}

func (a valueReflectionsBelongsToValueTx) Unscoped() *valueReflectionsBelongsToValueTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type valueReflectionsDo struct{ gen.DO }

func (v valueReflectionsDo) Debug() *valueReflectionsDo {
	return v.withDO(v.DO.Debug())
}

func (v valueReflectionsDo) WithContext(ctx context.Context) *valueReflectionsDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v valueReflectionsDo) ReadDB() *valueReflectionsDo {
	return v.Clauses(dbresolver.Read)
}

func (v valueReflectionsDo) WriteDB() *valueReflectionsDo {
	return v.Clauses(dbresolver.Write)
}

func (v valueReflectionsDo) Session(config *gorm.Session) *valueReflectionsDo {
	return v.withDO(v.DO.Session(config))
}

func (v valueReflectionsDo) Clauses(conds ...clause.Expression) *valueReflectionsDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v valueReflectionsDo) Returning(value interface{}, columns ...string) *valueReflectionsDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v valueReflectionsDo) Not(conds ...gen.Condition) *valueReflectionsDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v valueReflectionsDo) Or(conds ...gen.Condition) *valueReflectionsDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v valueReflectionsDo) Select(conds ...field.Expr) *valueReflectionsDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v valueReflectionsDo) Where(conds ...gen.Condition) *valueReflectionsDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v valueReflectionsDo) Order(conds ...field.Expr) *valueReflectionsDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v valueReflectionsDo) Distinct(cols ...field.Expr) *valueReflectionsDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v valueReflectionsDo) Omit(cols ...field.Expr) *valueReflectionsDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v valueReflectionsDo) Join(table schema.Tabler, on ...field.Expr) *valueReflectionsDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v valueReflectionsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *valueReflectionsDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v valueReflectionsDo) RightJoin(table schema.Tabler, on ...field.Expr) *valueReflectionsDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v valueReflectionsDo) Group(cols ...field.Expr) *valueReflectionsDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v valueReflectionsDo) Having(conds ...gen.Condition) *valueReflectionsDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v valueReflectionsDo) Limit(limit int) *valueReflectionsDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v valueReflectionsDo) Offset(offset int) *valueReflectionsDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v valueReflectionsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *valueReflectionsDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v valueReflectionsDo) Unscoped() *valueReflectionsDo {
	return v.withDO(v.DO.Unscoped())
}

func (v valueReflectionsDo) Create(values ...*model.ValueReflections) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v valueReflectionsDo) CreateInBatches(values []*model.ValueReflections, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v valueReflectionsDo) Save(values ...*model.ValueReflections) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v valueReflectionsDo) First() (*model.ValueReflections, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ValueReflections), nil
	}
}

func (v valueReflectionsDo) Take() (*model.ValueReflections, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ValueReflections), nil
	}
}

func (v valueReflectionsDo) Last() (*model.ValueReflections, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ValueReflections), nil
	}
}

func (v valueReflectionsDo) Find() ([]*model.ValueReflections, error) {
	result, err := v.DO.Find()
	return result.([]*model.ValueReflections), err
}

func (v valueReflectionsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ValueReflections, err error) {
	buf := make([]*model.ValueReflections, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v valueReflectionsDo) FindInBatches(result *[]*model.ValueReflections, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v valueReflectionsDo) Attrs(attrs ...field.AssignExpr) *valueReflectionsDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v valueReflectionsDo) Assign(attrs ...field.AssignExpr) *valueReflectionsDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v valueReflectionsDo) Joins(fields ...field.RelationField) *valueReflectionsDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v valueReflectionsDo) Preload(fields ...field.RelationField) *valueReflectionsDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v valueReflectionsDo) FirstOrInit() (*model.ValueReflections, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ValueReflections), nil
	}
}

func (v valueReflectionsDo) FirstOrCreate() (*model.ValueReflections, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ValueReflections), nil
	}
}

func (v valueReflectionsDo) FindByPage(offset int, limit int) (result []*model.ValueReflections, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v valueReflectionsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v valueReflectionsDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v valueReflectionsDo) Delete(models ...*model.ValueReflections) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *valueReflectionsDo) withDO(do gen.Dao) *valueReflectionsDo {
	v.DO = *do.(*gen.DO)
	return v
}
