// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mindsteps/database/model"
)

func newUserStreaks(db *gorm.DB, opts ...gen.DOOption) userStreaks {
	_userStreaks := userStreaks{}

	_userStreaks.userStreaksDo.UseDB(db, opts...)
	_userStreaks.userStreaksDo.UseModel(&model.UserStreaks{})

	tableName := _userStreaks.userStreaksDo.TableName()
	_userStreaks.ALL = field.NewAsterisk(tableName)
	_userStreaks.ID = field.NewUint(tableName, "id")
	_userStreaks.UserID = field.NewUint(tableName, "user_id")
	_userStreaks.StreakType = field.NewString(tableName, "streak_type")
	_userStreaks.CurrentStreak = field.NewInt(tableName, "current_streak")
	_userStreaks.LongestStreak = field.NewInt(tableName, "longest_streak")
	_userStreaks.LastActivityDate = field.NewTime(tableName, "last_activity_date")
	_userStreaks.CreatedAt = field.NewTime(tableName, "created_at")
	_userStreaks.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userStreaks.User = userStreaksBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.Users"),
	}

	_userStreaks.fillFieldMap()

	return _userStreaks
}

type userStreaks struct {
	userStreaksDo userStreaksDo

	ALL              field.Asterisk
	ID               field.Uint
	UserID           field.Uint
	StreakType       field.String
	CurrentStreak    field.Int
	LongestStreak    field.Int
	LastActivityDate field.Time
	CreatedAt        field.Time
	UpdatedAt        field.Time
	User             userStreaksBelongsToUser

	fieldMap map[string]field.Expr
}

func (u userStreaks) Table(newTableName string) *userStreaks {
	u.userStreaksDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userStreaks) As(alias string) *userStreaks {
	u.userStreaksDo.DO = *(u.userStreaksDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userStreaks) updateTableName(table string) *userStreaks {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint(table, "id")
	u.UserID = field.NewUint(table, "user_id")
	u.StreakType = field.NewString(table, "streak_type")
	u.CurrentStreak = field.NewInt(table, "current_streak")
	u.LongestStreak = field.NewInt(table, "longest_streak")
	u.LastActivityDate = field.NewTime(table, "last_activity_date")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userStreaks) WithContext(ctx context.Context) *userStreaksDo {
	return u.userStreaksDo.WithContext(ctx)
}

func (u userStreaks) TableName() string { return u.userStreaksDo.TableName() }

func (u userStreaks) Alias() string { return u.userStreaksDo.Alias() }

func (u userStreaks) Columns(cols ...field.Expr) gen.Columns { return u.userStreaksDo.Columns(cols...) }

func (u *userStreaks) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userStreaks) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 9)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["streak_type"] = u.StreakType
	u.fieldMap["current_streak"] = u.CurrentStreak
	u.fieldMap["longest_streak"] = u.LongestStreak
	u.fieldMap["last_activity_date"] = u.LastActivityDate
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt

}

func (u userStreaks) clone(db *gorm.DB) userStreaks {
	u.userStreaksDo.ReplaceConnPool(db.Statement.ConnPool)
	u.User.db = db.Session(&gorm.Session{Initialized: true})
	u.User.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u userStreaks) replaceDB(db *gorm.DB) userStreaks {
	u.userStreaksDo.ReplaceDB(db)
	u.User.db = db.Session(&gorm.Session{})
	return u
}

type userStreaksBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a userStreaksBelongsToUser) Where(conds ...field.Expr) *userStreaksBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userStreaksBelongsToUser) WithContext(ctx context.Context) *userStreaksBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userStreaksBelongsToUser) Session(session *gorm.Session) *userStreaksBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a userStreaksBelongsToUser) Model(m *model.UserStreaks) *userStreaksBelongsToUserTx {
	return &userStreaksBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a userStreaksBelongsToUser) Unscoped() *userStreaksBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type userStreaksBelongsToUserTx struct{ tx *gorm.Association }

func (a userStreaksBelongsToUserTx) Find() (result *model.Users, err error) {
	return result, a.tx.Find(&result)
}

func (a userStreaksBelongsToUserTx) Append(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userStreaksBelongsToUserTx) Replace(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userStreaksBelongsToUserTx) Delete(values ...*model.Users) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userStreaksBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a userStreaksBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a userStreaksBelongsToUserTx) Unscoped() *userStreaksBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userStreaksDo struct{ gen.DO }

func (u userStreaksDo) Debug() *userStreaksDo {
	return u.withDO(u.DO.Debug())
}

func (u userStreaksDo) WithContext(ctx context.Context) *userStreaksDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userStreaksDo) ReadDB() *userStreaksDo {
	return u.Clauses(dbresolver.Read)
}

func (u userStreaksDo) WriteDB() *userStreaksDo {
	return u.Clauses(dbresolver.Write)
}

func (u userStreaksDo) Session(config *gorm.Session) *userStreaksDo {
	return u.withDO(u.DO.Session(config))
}

func (u userStreaksDo) Clauses(conds ...clause.Expression) *userStreaksDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userStreaksDo) Returning(value interface{}, columns ...string) *userStreaksDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userStreaksDo) Not(conds ...gen.Condition) *userStreaksDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userStreaksDo) Or(conds ...gen.Condition) *userStreaksDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userStreaksDo) Select(conds ...field.Expr) *userStreaksDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userStreaksDo) Where(conds ...gen.Condition) *userStreaksDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userStreaksDo) Order(conds ...field.Expr) *userStreaksDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userStreaksDo) Distinct(cols ...field.Expr) *userStreaksDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userStreaksDo) Omit(cols ...field.Expr) *userStreaksDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userStreaksDo) Join(table schema.Tabler, on ...field.Expr) *userStreaksDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userStreaksDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userStreaksDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userStreaksDo) RightJoin(table schema.Tabler, on ...field.Expr) *userStreaksDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userStreaksDo) Group(cols ...field.Expr) *userStreaksDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userStreaksDo) Having(conds ...gen.Condition) *userStreaksDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userStreaksDo) Limit(limit int) *userStreaksDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userStreaksDo) Offset(offset int) *userStreaksDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userStreaksDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userStreaksDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userStreaksDo) Unscoped() *userStreaksDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userStreaksDo) Create(values ...*model.UserStreaks) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userStreaksDo) CreateInBatches(values []*model.UserStreaks, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userStreaksDo) Save(values ...*model.UserStreaks) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userStreaksDo) First() (*model.UserStreaks, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserStreaks), nil
	}
}

func (u userStreaksDo) Take() (*model.UserStreaks, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserStreaks), nil
	}
}

func (u userStreaksDo) Last() (*model.UserStreaks, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserStreaks), nil
	}
}

func (u userStreaksDo) Find() ([]*model.UserStreaks, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserStreaks), err
}

func (u userStreaksDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserStreaks, err error) {
	buf := make([]*model.UserStreaks, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userStreaksDo) FindInBatches(result *[]*model.UserStreaks, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userStreaksDo) Attrs(attrs ...field.AssignExpr) *userStreaksDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userStreaksDo) Assign(attrs ...field.AssignExpr) *userStreaksDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userStreaksDo) Joins(fields ...field.RelationField) *userStreaksDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userStreaksDo) Preload(fields ...field.RelationField) *userStreaksDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userStreaksDo) FirstOrInit() (*model.UserStreaks, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserStreaks), nil
	}
}

func (u userStreaksDo) FirstOrCreate() (*model.UserStreaks, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserStreaks), nil
	}
}

func (u userStreaksDo) FindByPage(offset int, limit int) (result []*model.UserStreaks, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userStreaksDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userStreaksDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userStreaksDo) Delete(models ...*model.UserStreaks) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userStreaksDo) withDO(do gen.Dao) *userStreaksDo {
	u.DO = *do.(*gen.DO)
	return u
}
