// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAIJournalDetailedAnalysis = "ai_journal_detailed_analysis"

// AIJournalDetailedAnalysis mapped from table <ai_journal_detailed_analysis>
type AIJournalDetailedAnalysis struct {
	ID                   uint      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	JournalID            uint      `gorm:"column:journal_id;type:integer;not null" json:"journal_id"`
	UserID               uint      `gorm:"column:user_id;type:integer;not null" json:"user_id"`
	OverallSentiment     *float64  `gorm:"column:overall_sentiment;type:numeric(3,2)" json:"overall_sentiment"`
	PrimaryEmotions      string    `gorm:"column:primary_emotions;type:text" json:"primary_emotions"`
	EmotionIntensity     *float64  `gorm:"column:emotion_intensity;type:numeric(3,2)" json:"emotion_intensity"`
	EmotionalDepthScore  *int      `gorm:"column:emotional_depth_score;type:integer" json:"emotional_depth_score"`
	SelfReflectionScore  *int      `gorm:"column:self_reflection_score;type:integer" json:"self_reflection_score"`
	GoalAlignmentScore   *int      `gorm:"column:goal_alignment_score;type:integer" json:"goal_alignment_score"`
	GratitudeScore       *int      `gorm:"column:gratitude_score;type:integer" json:"gratitude_score"`
	ProblemSolvingScore  *int      `gorm:"column:problem_solving_score;type:integer" json:"problem_solving_score"`
	MindfulnessScore     *int      `gorm:"column:mindfulness_score;type:integer" json:"mindfulness_score"`
	StressIndicators     string    `gorm:"column:stress_indicators;type:text" json:"stress_indicators"`
	PositivePatterns     string    `gorm:"column:positive_patterns;type:text" json:"positive_patterns"`
	ConcerningPatterns   string    `gorm:"column:concerning_patterns;type:text" json:"concerning_patterns"`
	GrowthIndicators     string    `gorm:"column:growth_indicators;type:text" json:"growth_indicators"`
	PersonalizedFeedback string    `gorm:"column:personalized_feedback;type:text" json:"personalized_feedback"`
	SuggestedActions     string    `gorm:"column:suggested_actions;type:text" json:"suggested_actions"`
	RecommendedLessons   string    `gorm:"column:recommended_lessons;type:text" json:"recommended_lessons"`
	TotalWeightedScore   *float64  `gorm:"column:total_weighted_score;type:numeric(5,2)" json:"total_weighted_score"`
	BonusPoints          int       `gorm:"column:bonus_points;type:integer" json:"bonus_points"`
	FinalPoints          *int      `gorm:"column:final_points;type:integer" json:"final_points"`
	AiConfidence         *float64  `gorm:"column:ai_confidence;type:numeric(3,2)" json:"ai_confidence"`
	ProcessingVersion    string    `gorm:"column:processing_version;type:character varying(10);default:v1.0" json:"processing_version"`
	ProcessingDuration   *int      `gorm:"column:processing_duration;type:integer" json:"processing_duration"`
	CreatedAt            time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	Journal              *Journals `gorm:"foreignKey:journal_id;references:id" json:"journal"`
	User                 *Users    `gorm:"foreignKey:user_id;references:id" json:"user"`
}

// TableName AIJournalDetailedAnalysis's table name
func (*AIJournalDetailedAnalysis) TableName() string {
	return TableNameAIJournalDetailedAnalysis
}
