// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAIMoodAnalysis = "ai_mood_analysis"

// AIMoodAnalysis mapped from table <ai_mood_analysis>
type AIMoodAnalysis struct {
	ID                         uint         `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	MoodEntryID                uint         `gorm:"column:mood_entry_id;type:integer;not null" json:"mood_entry_id"`
	UserID                     uint         `gorm:"column:user_id;type:integer;not null" json:"user_id"`
	MoodConsistencyScore       *int         `gorm:"column:mood_consistency_score;type:integer" json:"mood_consistency_score"`
	TriggerPatternScore        *int         `gorm:"column:trigger_pattern_score;type:integer" json:"trigger_pattern_score"`
	CopingEffectivenessScore   *int         `gorm:"column:coping_effectiveness_score;type:integer" json:"coping_effectiveness_score"`
	EmotionalIntelligenceScore *int         `gorm:"column:emotional_intelligence_score;type:integer" json:"emotional_intelligence_score"`
	DetectedPatterns           string       `gorm:"column:detected_patterns;type:text" json:"detected_patterns"`
	ImprovementSuggestions     string       `gorm:"column:improvement_suggestions;type:text" json:"improvement_suggestions"`
	WarningFlags               string       `gorm:"column:warning_flags;type:text" json:"warning_flags"`
	PointsEarned               int          `gorm:"column:points_earned;type:integer" json:"points_earned"`
	CreatedAt                  time.Time    `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	MoodEntry                  *MoodEntries `gorm:"foreignKey:mood_entry_id;references:id" json:"mood_entry"`
	User                       *Users       `gorm:"foreignKey:user_id;references:id" json:"user"`
}

// TableName AIMoodAnalysis's table name
func (*AIMoodAnalysis) TableName() string {
	return TableNameAIMoodAnalysis
}
