// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAIProgressTracking = "ai_progress_tracking"

// AIProgressTracking mapped from table <ai_progress_tracking>
type AIProgressTracking struct {
	ID                        uint      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	UserID                    uint      `gorm:"column:user_id;type:integer;not null" json:"user_id"`
	AnalysisPeriod            string    `gorm:"column:analysis_period;type:character varying(20)" json:"analysis_period"`
	PeriodStart               time.Time `gorm:"column:period_start;type:date;not null" json:"period_start"`
	PeriodEnd                 time.Time `gorm:"column:period_end;type:date;not null" json:"period_end"`
	JournalConsistencyScore   *int      `gorm:"column:journal_consistency_score;type:integer" json:"journal_consistency_score"`
	MoodStabilityTrend        *float64  `gorm:"column:mood_stability_trend;type:numeric(3,2)" json:"mood_stability_trend"`
	GoalProgressRate          *float64  `gorm:"column:goal_progress_rate;type:numeric(5,2)" json:"goal_progress_rate"`
	MeditationRegularityScore *int      `gorm:"column:meditation_regularity_score;type:integer" json:"meditation_regularity_score"`
	OverallWellbeingTrend     *float64  `gorm:"column:overall_wellbeing_trend;type:numeric(3,2)" json:"overall_wellbeing_trend"`
	KeyImprovements           string    `gorm:"column:key_improvements;type:text" json:"key_improvements"`
	AreasNeedingAttention     string    `gorm:"column:areas_needing_attention;type:text" json:"areas_needing_attention"`
	BehavioralChangesDetected string    `gorm:"column:behavioral_changes_detected;type:text" json:"behavioral_changes_detected"`
	RecommendedFocusAreas     string    `gorm:"column:recommended_focus_areas;type:text" json:"recommended_focus_areas"`
	PeriodTotalPoints         *int      `gorm:"column:period_total_points;type:integer" json:"period_total_points"`
	ImprovementBonusPoints    int       `gorm:"column:improvement_bonus_points;type:integer" json:"improvement_bonus_points"`
	ConsistencyBonusPoints    int       `gorm:"column:consistency_bonus_points;type:integer" json:"consistency_bonus_points"`
	GeneratedAt               time.Time `gorm:"column:generated_at;type:timestamp without time zone;default:now()" json:"generated_at"`
	User                      *Users    `gorm:"foreignKey:user_id;references:id" json:"user"`
}

// TableName AIProgressTracking's table name
func (*AIProgressTracking) TableName() string {
	return TableNameAIProgressTracking
}
