// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAuthOTP = "auth_otp"

// AuthOTP mapped from table <auth_otp>
type AuthOTP struct {
	ID        uint           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID    uint           `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	MessageID uint           `gorm:"column:message_id;type:bigint;not null" json:"message_id"`
	Otp       string         `gorm:"column:otp;type:character varying(255);not null" json:"otp"`
	ExpiredAt time.Time      `gorm:"column:expired_at;type:timestamp with time zone;not null" json:"expired_at"`
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	User      *Users         `gorm:"foreignKey:user_id;references:id" json:"user"`
}

// TableName AuthOTP's table name
func (*AuthOTP) TableName() string {
	return TableNameAuthOTP
}
