// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLessonReactions = "lesson_reactions"

// LessonReactions mapped from table <lesson_reactions>
type LessonReactions struct {
	ID           uint      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	LessonID     uint      `gorm:"column:lesson_id;type:integer;not null" json:"lesson_id"`
	UserID       uint      `gorm:"column:user_id;type:integer;not null" json:"user_id"`
	ReactionType string    `gorm:"column:reaction_type;type:character varying(20)" json:"reaction_type"`
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	Lesson       *Lessons  `gorm:"foreignKey:lesson_id;references:id" json:"lesson"`
	User         *Users    `gorm:"foreignKey:user_id;references:id" json:"user"`
}

// TableName LessonReactions's table name
func (*LessonReactions) TableName() string {
	return TableNameLessonReactions
}
