// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLessonComments = "lesson_comments"

// LessonComments mapped from table <lesson_comments>
type LessonComments struct {
	ID        uint      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	LessonID  uint      `gorm:"column:lesson_id;type:integer;not null" json:"lesson_id"`
	UserID    uint      `gorm:"column:user_id;type:integer;not null" json:"user_id"`
	ParentID  *uint     `gorm:"column:parent_id;type:integer" json:"parent_id"`
	Content   string    `gorm:"column:content;type:text;not null" json:"content"`
	IsEdited  bool      `gorm:"column:is_edited;type:boolean" json:"is_edited"`
	IsDeleted bool      `gorm:"column:is_deleted;type:boolean" json:"is_deleted"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp without time zone;default:now()" json:"updated_at"`
	Lesson    *Lessons  `gorm:"foreignKey:lesson_id;references:id" json:"lesson"`
	User      *Users    `gorm:"foreignKey:user_id;references:id" json:"user"`
}

// TableName LessonComments's table name
func (*LessonComments) TableName() string {
	return TableNameLessonComments
}
