// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLessonCategories = "lesson_categories"

// LessonCategories mapped from table <lesson_categories>
type LessonCategories struct {
	ID          uint      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;type:character varying(100);not null" json:"name"`
	Description string    `gorm:"column:description;type:text" json:"description"`
	Icon        string    `gorm:"column:icon;type:character varying(50)" json:"icon"`
	Color       string    `gorm:"column:color;type:character varying(7)" json:"color"`
	SortOrder   *int      `gorm:"column:sort_order;type:integer" json:"sort_order"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
}

// TableName LessonCategories's table name
func (*LessonCategories) TableName() string {
	return TableNameLessonCategories
}
