// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameErrorLogs = "mindstep.error_logs"

// ErrorLogs mapped from table <mindstep.error_logs>
type ErrorLogs struct {
	ID              uint      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID          uint      `gorm:"column:user_id;type:bigint" json:"user_id"`
	ErrorType       string    `gorm:"column:error_type;type:character varying(50)" json:"error_type"`
	ErrorMessage    string    `gorm:"column:error_message;type:text" json:"error_message"`
	StackTrace      string    `gorm:"column:stack_trace;type:text" json:"stack_trace"`
	RequestURL      string    `gorm:"column:request_url;type:text" json:"request_url"`
	RequestMethod   string    `gorm:"column:request_method;type:character varying(10)" json:"request_method"`
	RequestBody     string    `gorm:"column:request_body;type:text" json:"request_body"`
	IPAddress       string    `gorm:"column:ip_address;type:inet" json:"ip_address"`
	UserAgent       string    `gorm:"column:user_agent;type:text" json:"user_agent"`
	IsResolved      bool      `gorm:"column:is_resolved;type:boolean" json:"is_resolved"`
	ResolvedAt      time.Time `gorm:"column:resolved_at;type:timestamp without time zone" json:"resolved_at"`
	ResolvedByID    uint      `gorm:"column:resolved_by_id;type:bigint" json:"resolved_by_id"`
	ResolutionNotes string    `gorm:"column:resolution_notes;type:text" json:"resolution_notes"`
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
}

// TableName ErrorLogs's table name
func (*ErrorLogs) TableName() string {
	return TableNameErrorLogs
}
