// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameRoles = "mindstep.roles"

// Roles mapped from table <mindstep.roles>
type Roles struct {
	ID          uint           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Level       int16          `gorm:"column:level;type:smallint;not null" json:"level"`
	Code        string         `gorm:"column:code;type:character varying(20);not null" json:"code"`
	Name        string         `gorm:"column:name;type:character varying(50);not null" json:"name"`
	Permissions datatypes.JSON `gorm:"column:permissions;type:jsonb;default:{}" json:"permissions"`
	CreatedByID uint           `gorm:"column:created_by_id;type:bigint" json:"created_by_id"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	UpdatedByID uint           `gorm:"column:updated_by_id;type:bigint" json:"updated_by_id"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp without time zone;default:now()" json:"updated_at"`
	CreatedBy   *Users         `gorm:"foreignKey:created_by_id;references:id" json:"CreatedBy"`
	UpdatedBy   *Users         `gorm:"foreignKey:updated_by_id;references:id" json:"UpdatedBy"`
}

// TableName Roles's table name
func (*Roles) TableName() string {
	return TableNameRoles
}
