// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSystemSettings = "mindstep.system_settings"

// SystemSettings mapped from table <mindstep.system_settings>
type SystemSettings struct {
	ID           int       `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	SettingKey   string    `gorm:"column:setting_key;type:character varying(100);not null" json:"setting_key"`
	SettingValue string    `gorm:"column:setting_value;type:text" json:"setting_value"`
	SettingType  string    `gorm:"column:setting_type;type:character varying(20)" json:"setting_type"`
	Description  string    `gorm:"column:description;type:text" json:"description"`
	IsPublic     bool      `gorm:"column:is_public;type:boolean" json:"is_public"`
	IsEditable   bool      `gorm:"column:is_editable;type:boolean;default:true" json:"is_editable"`
	UpdatedByID  uint      `gorm:"column:updated_by_id;type:bigint" json:"updated_by_id"`
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamp without time zone;default:now()" json:"updated_at"`
	UpdatedBy    *Users    `gorm:"foreignKey:updated_by_id;references:id" json:"UpdatedBy"`
}

// TableName SystemSettings's table name
func (*SystemSettings) TableName() string {
	return TableNameSystemSettings
}
