// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDetectedPatterns = "mindstep.detected_patterns"

// DetectedPatterns mapped from table <mindstep.detected_patterns>
type DetectedPatterns struct {
	ID                   uint      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID               uint      `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	PatternType          string    `gorm:"column:pattern_type;type:character varying(50);not null" json:"pattern_type"`
	PatternCategory      string    `gorm:"column:pattern_category;type:character varying(30)" json:"pattern_category"`
	PatternName          string    `gorm:"column:pattern_name;type:character varying(255)" json:"pattern_name"`
	Description          string    `gorm:"column:description;type:text" json:"description"`
	DetectedFrom         string    `gorm:"column:detected_from;type:text[]" json:"detected_from"`
	Frequency            string    `gorm:"column:frequency;type:character varying(20)" json:"frequency"`
	ConfidenceScore      float64   `gorm:"column:confidence_score;type:numeric(3,2)" json:"confidence_score"`
	FirstDetected        time.Time `gorm:"column:first_detected;type:date" json:"first_detected"`
	LastDetected         time.Time `gorm:"column:last_detected;type:date" json:"last_detected"`
	OccurrenceCount      int       `gorm:"column:occurrence_count;type:integer;default:1" json:"occurrence_count"`
	Severity             string    `gorm:"column:severity;type:character varying(20)" json:"severity"`
	RelatedValueIds      string    `gorm:"column:related_value_ids;type:bigint[]" json:"related_value_ids"`
	EmotionalImpactScore int       `gorm:"column:emotional_impact_score;type:integer" json:"emotional_impact_score"`
	SuggestedActions     string    `gorm:"column:suggested_actions;type:text[]" json:"suggested_actions"`
	RecommendedLessonIds string    `gorm:"column:recommended_lesson_ids;type:bigint[]" json:"recommended_lesson_ids"`
	IsResolved           bool      `gorm:"column:is_resolved;type:boolean" json:"is_resolved"`
	ResolvedAt           time.Time `gorm:"column:resolved_at;type:timestamp without time zone" json:"resolved_at"`
	UserAcknowledged     bool      `gorm:"column:user_acknowledged;type:boolean" json:"user_acknowledged"`
	AcknowledgedAt       time.Time `gorm:"column:acknowledged_at;type:timestamp without time zone" json:"acknowledged_at"`
	CreatedAt            time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at;type:timestamp without time zone;default:now()" json:"updated_at"`
}

// TableName DetectedPatterns's table name
func (*DetectedPatterns) TableName() string {
	return TableNameDetectedPatterns
}
