// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameProgressReports = "mindstep.progress_reports"

// ProgressReports mapped from table <mindstep.progress_reports>
type ProgressReports struct {
	ID                          uint           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID                      uint           `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	ReportType                  string         `gorm:"column:report_type;type:character varying(20)" json:"report_type"`
	PeriodStart                 time.Time      `gorm:"column:period_start;type:date;not null" json:"period_start"`
	PeriodEnd                   time.Time      `gorm:"column:period_end;type:date;not null" json:"period_end"`
	OverallWellbeingScore       int            `gorm:"column:overall_wellbeing_score;type:integer" json:"overall_wellbeing_score"`
	MoodSummary                 datatypes.JSON `gorm:"column:mood_summary;type:jsonb" json:"mood_summary"`
	JournalInsights             datatypes.JSON `gorm:"column:journal_insights;type:jsonb" json:"journal_insights"`
	GoalProgress                datatypes.JSON `gorm:"column:goal_progress;type:jsonb" json:"goal_progress"`
	MeditationSummary           datatypes.JSON `gorm:"column:meditation_summary;type:jsonb" json:"meditation_summary"`
	ConsciousnessProgression    datatypes.JSON `gorm:"column:consciousness_progression;type:jsonb" json:"consciousness_progression"`
	KeyAchievements             string         `gorm:"column:key_achievements;type:text[]" json:"key_achievements"`
	AreasForImprovement         string         `gorm:"column:areas_for_improvement;type:text[]" json:"areas_for_improvement"`
	PersonalizedRecommendations string         `gorm:"column:personalized_recommendations;type:text[]" json:"personalized_recommendations"`
	ChartData                   datatypes.JSON `gorm:"column:chart_data;type:jsonb" json:"chart_data"`
	PdfURL                      string         `gorm:"column:pdf_url;type:character varying(500)" json:"pdf_url"`
	IsExported                  bool           `gorm:"column:is_exported;type:boolean" json:"is_exported"`
	ExportedAt                  time.Time      `gorm:"column:exported_at;type:timestamp without time zone" json:"exported_at"`
	GeneratedAt                 time.Time      `gorm:"column:generated_at;type:timestamp without time zone;default:now()" json:"generated_at"`
	User                        *Users         `gorm:"foreignKey:user_id;references:id" json:"User"`
}

// TableName ProgressReports's table name
func (*ProgressReports) TableName() string {
	return TableNameProgressReports
}
