// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserLessonProgress = "mindstep.user_lesson_progress"

// UserLessonProgress mapped from table <mindstep.user_lesson_progress>
type UserLessonProgress struct {
	ID                 uint      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	LessonID           uint      `gorm:"column:lesson_id;type:bigint;not null" json:"lesson_id"`
	UserID             uint      `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	ProgressPercentage int       `gorm:"column:progress_percentage;type:integer" json:"progress_percentage"`
	Status             string    `gorm:"column:status;type:character varying(20);default:not_started" json:"status"`
	TimeSpent          int       `gorm:"column:time_spent;type:integer" json:"time_spent"`
	LastAccessed       time.Time `gorm:"column:last_accessed;type:timestamp without time zone" json:"last_accessed"`
	CompletionDate     time.Time `gorm:"column:completion_date;type:timestamp without time zone" json:"completion_date"`
	Rating             int       `gorm:"column:rating;type:integer" json:"rating"`
	ReviewText         string    `gorm:"column:review_text;type:text" json:"review_text"`
	IsBookmarked       bool      `gorm:"column:is_bookmarked;type:boolean" json:"is_bookmarked"`
	CreatedAt          time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at;type:timestamp without time zone;default:now()" json:"updated_at"`
}

// TableName UserLessonProgress's table name
func (*UserLessonProgress) TableName() string {
	return TableNameUserLessonProgress
}
