// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameAIJournalDetailedAnalysis = "mindstep.ai_journal_detailed_analysis"

// AIJournalDetailedAnalysis mapped from table <mindstep.ai_journal_detailed_analysis>
type AIJournalDetailedAnalysis struct {
	ID                   uint           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	JournalID            uint           `gorm:"column:journal_id;type:bigint;not null" json:"journal_id"`
	UserID               uint           `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	OverallSentiment     float64        `gorm:"column:overall_sentiment;type:numeric(4,2)" json:"overall_sentiment"`
	PrimaryEmotions      datatypes.JSON `gorm:"column:primary_emotions;type:jsonb" json:"primary_emotions"`
	EmotionIntensity     float64        `gorm:"column:emotion_intensity;type:numeric(3,2)" json:"emotion_intensity"`
	EmotionalDepthScore  int            `gorm:"column:emotional_depth_score;type:integer" json:"emotional_depth_score"`
	SelfReflectionScore  int            `gorm:"column:self_reflection_score;type:integer" json:"self_reflection_score"`
	GoalAlignmentScore   int            `gorm:"column:goal_alignment_score;type:integer" json:"goal_alignment_score"`
	GratitudeScore       int            `gorm:"column:gratitude_score;type:integer" json:"gratitude_score"`
	ProblemSolvingScore  int            `gorm:"column:problem_solving_score;type:integer" json:"problem_solving_score"`
	MindfulnessScore     int            `gorm:"column:mindfulness_score;type:integer" json:"mindfulness_score"`
	StressIndicators     string         `gorm:"column:stress_indicators;type:text[]" json:"stress_indicators"`
	PositivePatterns     string         `gorm:"column:positive_patterns;type:text[]" json:"positive_patterns"`
	ConcerningPatterns   string         `gorm:"column:concerning_patterns;type:text[]" json:"concerning_patterns"`
	GrowthIndicators     string         `gorm:"column:growth_indicators;type:text[]" json:"growth_indicators"`
	PersonalizedFeedback string         `gorm:"column:personalized_feedback;type:text" json:"personalized_feedback"`
	SuggestedActions     string         `gorm:"column:suggested_actions;type:text[]" json:"suggested_actions"`
	RecommendedLessonIds string         `gorm:"column:recommended_lesson_ids;type:bigint[]" json:"recommended_lesson_ids"`
	TotalWeightedScore   float64        `gorm:"column:total_weighted_score;type:numeric(5,2)" json:"total_weighted_score"`
	BonusPoints          int            `gorm:"column:bonus_points;type:integer" json:"bonus_points"`
	FinalPoints          int            `gorm:"column:final_points;type:integer" json:"final_points"`
	AiConfidence         float64        `gorm:"column:ai_confidence;type:numeric(3,2)" json:"ai_confidence"`
	ProcessingVersion    string         `gorm:"column:processing_version;type:character varying(10);default:v1.0" json:"processing_version"`
	ProcessingDuration   int            `gorm:"column:processing_duration;type:integer" json:"processing_duration"`
	ModelName            string         `gorm:"column:model_name;type:character varying(50)" json:"model_name"`
	CreatedAt            time.Time      `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
}

// TableName AIJournalDetailedAnalysis's table name
func (*AIJournalDetailedAnalysis) TableName() string {
	return TableNameAIJournalDetailedAnalysis
}
