// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameNotifications = "mindstep.notifications"

// Notifications mapped from table <mindstep.notifications>
type Notifications struct {
	ID               uint           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID           uint           `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	NotificationType string         `gorm:"column:notification_type;type:character varying(50)" json:"notification_type"`
	Title            string         `gorm:"column:title;type:character varying(255);not null" json:"title"`
	Message          string         `gorm:"column:message;type:text" json:"message"`
	ActionURL        string         `gorm:"column:action_url;type:character varying(500)" json:"action_url"`
	ActionLabel      string         `gorm:"column:action_label;type:character varying(50)" json:"action_label"`
	IsRead           bool           `gorm:"column:is_read;type:boolean" json:"is_read"`
	ReadAt           time.Time      `gorm:"column:read_at;type:timestamp without time zone" json:"read_at"`
	ScheduledFor     time.Time      `gorm:"column:scheduled_for;type:timestamp without time zone" json:"scheduled_for"`
	SentAt           time.Time      `gorm:"column:sent_at;type:timestamp without time zone" json:"sent_at"`
	Metadata         datatypes.JSON `gorm:"column:metadata;type:jsonb" json:"metadata"`
	Priority         string         `gorm:"column:priority;type:character varying(20);default:normal" json:"priority"`
	CreatedAt        time.Time      `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	User             *Users         `gorm:"foreignKey:user_id;references:id" json:"User"`
}

// TableName Notifications's table name
func (*Notifications) TableName() string {
	return TableNameNotifications
}
