// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserPreferences = "mindstep.user_preferences"

// UserPreferences mapped from table <mindstep.user_preferences>
type UserPreferences struct {
	ID                       uint      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID                   uint      `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	ReminderJournal          bool      `gorm:"column:reminder_journal;type:boolean;default:true" json:"reminder_journal"`
	ReminderMoodCheck        bool      `gorm:"column:reminder_mood_check;type:boolean;default:true" json:"reminder_mood_check"`
	ReminderMeditation       bool      `gorm:"column:reminder_meditation;type:boolean;default:true" json:"reminder_meditation"`
	ReminderGoalReview       bool      `gorm:"column:reminder_goal_review;type:boolean;default:true" json:"reminder_goal_review"`
	ReminderTime             string    `gorm:"column:reminder_time;type:character varying(5);default:20:00" json:"reminder_time"`
	NotificationEmail        bool      `gorm:"column:notification_email;type:boolean;default:true" json:"notification_email"`
	NotificationPush         bool      `gorm:"column:notification_push;type:boolean;default:true" json:"notification_push"`
	NotificationInsights     bool      `gorm:"column:notification_insights;type:boolean;default:true" json:"notification_insights"`
	NotificationAchievements bool      `gorm:"column:notification_achievements;type:boolean;default:true" json:"notification_achievements"`
	PrivacyLevel             string    `gorm:"column:privacy_level;type:character varying(20);default:private" json:"privacy_level"`
	DataSharing              bool      `gorm:"column:data_sharing;type:boolean" json:"data_sharing"`
	Theme                    string    `gorm:"column:theme;type:character varying(20);default:light" json:"theme"`
	Language                 string    `gorm:"column:language;type:character varying(5);default:mn" json:"language"`
	DateFormat               string    `gorm:"column:date_format;type:character varying(20);default:YYYY-MM-DD" json:"date_format"`
	AiAnalysisFrequency      string    `gorm:"column:ai_analysis_frequency;type:character varying(20);default:weekly" json:"ai_analysis_frequency"`
	AiSuggestionLevel        string    `gorm:"column:ai_suggestion_level;type:character varying(20);default:moderate" json:"ai_suggestion_level"`
	CreatedAt                time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	UpdatedAt                time.Time `gorm:"column:updated_at;type:timestamp without time zone;default:now()" json:"updated_at"`
	User                     *Users    `gorm:"foreignKey:user_id;references:id" json:"User"`
}

// TableName UserPreferences's table name
func (*UserPreferences) TableName() string {
	return TableNameUserPreferences
}
