// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserConsciousnessTracking = "mindstep.user_consciousness_tracking"

// UserConsciousnessTracking mapped from table <mindstep.user_consciousness_tracking>
type UserConsciousnessTracking struct {
	ID                 uint      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID             uint      `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	MeasurementDate    time.Time `gorm:"column:measurement_date;type:date;not null;default:CURRENT_DATE" json:"measurement_date"`
	ConsciousnessScore int       `gorm:"column:consciousness_score;type:integer;not null" json:"consciousness_score"`
	PrimaryLevelID     int       `gorm:"column:primary_level_id;type:integer" json:"primary_level_id"`
	DetectedFrom       string    `gorm:"column:detected_from;type:character varying(20)" json:"detected_from"`
	SourceID           uint      `gorm:"column:source_id;type:bigint" json:"source_id"`
	CalculationMethod  string    `gorm:"column:calculation_method;type:character varying(50)" json:"calculation_method"`
	ConfidenceScore    float64   `gorm:"column:confidence_score;type:numeric(3,2)" json:"confidence_score"`
	Notes              string    `gorm:"column:notes;type:text" json:"notes"`
	CreatedAt          time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
}

// TableName UserConsciousnessTracking's table name
func (*UserConsciousnessTracking) TableName() string {
	return TableNameUserConsciousnessTracking
}
