// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDataRetentionPolicies = "mindstep.data_retention_policies"

// DataRetentionPolicies mapped from table <mindstep.data_retention_policies>
type DataRetentionPolicies struct {
	ID               int       `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	TableName_       string    `gorm:"column:table_name;type:character varying(100);not null" json:"table_name"`
	RetentionDays    int       `gorm:"column:retention_days;type:integer;not null" json:"retention_days"`
	ArchiveAfterDays int       `gorm:"column:archive_after_days;type:integer" json:"archive_after_days"`
	AutoDelete       bool      `gorm:"column:auto_delete;type:boolean" json:"auto_delete"`
	DeletionMethod   string    `gorm:"column:deletion_method;type:character varying(50)" json:"deletion_method"`
	LastCleanupAt    time.Time `gorm:"column:last_cleanup_at;type:timestamp without time zone" json:"last_cleanup_at"`
	NextCleanupAt    time.Time `gorm:"column:next_cleanup_at;type:timestamp without time zone" json:"next_cleanup_at"`
	IsActive         bool      `gorm:"column:is_active;type:boolean;default:true" json:"is_active"`
	CreatedAt        time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:timestamp without time zone;default:now()" json:"updated_at"`
}

// TableName DataRetentionPolicies's table name
func (*DataRetentionPolicies) TableName() string {
	return TableNameDataRetentionPolicies
}
