// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMoodUnit = "mindstep.mood_unit"

// MoodUnit mapped from table <mindstep.mood_unit>
type MoodUnit struct {
	ID                   uint                  `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	CategoryID           uint                  `gorm:"column:category_id;type:bigint;not null" json:"category_id"`
	PlutchikID           uint                  `gorm:"column:plutchik_id;type:bigint" json:"plutchik_id"`
	CombinationID        uint                  `gorm:"column:combination_id;type:bigint" json:"combination_id"`
	Type                 string                `gorm:"column:type;type:character varying(20);not null" json:"type"`
	Description          string                `gorm:"column:description;type:text" json:"description"`
	DisplayNameMn        string                `gorm:"column:display_name_mn;type:character varying(100)" json:"display_name_mn"`
	DisplayNameEn        string                `gorm:"column:display_name_en;type:character varying(100)" json:"display_name_en"`
	DisplayColor         string                `gorm:"column:display_color;type:character(7)" json:"display_color"`
	DisplayEmoji         string                `gorm:"column:display_emoji;type:character varying(10)" json:"display_emoji"`
	HawkinsLevelID       int32                 `gorm:"column:hawkins_level_id;type:integer" json:"hawkins_level_id"`
	MoodCategories       *MoodCategories       `gorm:"foreignKey:category_id;references:id" json:"MoodCategories"`
	PlutchikEmotions     *PlutchikEmotions     `gorm:"foreignKey:plutchik_id;references:id" json:"PlutchikEmotions"`
	PlutchikCombinations *PlutchikCombinations `gorm:"foreignKey:combination_id;references:id" json:"PlutchikCombinations"`
}

// TableName MoodUnit's table name
func (*MoodUnit) TableName() string {
	return TableNameMoodUnit
}
