// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAIScoringCriteria = "mindstep.ai_scoring_criteria"

// AIScoringCriteria mapped from table <mindstep.ai_scoring_criteria>
type AIScoringCriteria struct {
	ID                int       `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	CriteriaName      string    `gorm:"column:criteria_name;type:character varying(100);not null" json:"criteria_name"`
	CriteriaCategory  string    `gorm:"column:criteria_category;type:character varying(50)" json:"criteria_category"`
	Description       string    `gorm:"column:description;type:text" json:"description"`
	MaxPoints         int       `gorm:"column:max_points;type:integer;default:10" json:"max_points"`
	Weight            float64   `gorm:"column:weight;type:numeric(3,2);default:1.0" json:"weight"`
	CalculationMethod string    `gorm:"column:calculation_method;type:text" json:"calculation_method"`
	IsActive          bool      `gorm:"column:is_active;type:boolean;default:true" json:"is_active"`
	CreatedAt         time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;type:timestamp without time zone;default:now()" json:"updated_at"`
}

// TableName AIScoringCriteria's table name
func (*AIScoringCriteria) TableName() string {
	return TableNameAIScoringCriteria
}
