// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRoleOwners = "mindstep.role_owners"

// RoleOwners mapped from table <mindstep.role_owners>
type RoleOwners struct {
	ID           uint      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	RoleID       uint      `gorm:"column:role_id;type:bigint;not null" json:"role_id"`
	OwnerID      uint      `gorm:"column:owner_id;type:bigint;not null" json:"owner_id"`
	Status       string    `gorm:"column:status;type:character varying(10);default:active" json:"status"`
	AssignedByID uint      `gorm:"column:assigned_by_id;type:bigint" json:"assigned_by_id"`
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	RevokedAt    time.Time `gorm:"column:revoked_at;type:timestamp without time zone" json:"revoked_at"`
	Role         *Roles    `gorm:"foreignKey:role_id;references:id" json:"Role"`
	Owner        *Users    `gorm:"foreignKey:owner_id;references:id" json:"Owner"`
	AssignedBy   *Users    `gorm:"foreignKey:assigned_by_id;references:id" json:"AssignedBy"`
}

// TableName RoleOwners's table name
func (*RoleOwners) TableName() string {
	return TableNameRoleOwners
}
