// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameAIWeeklyMoodDeepAnalysis = "mindstep.ai_weekly_mood_deep_analysis"

// AIWeeklyMoodDeepAnalysis mapped from table <mindstep.ai_weekly_mood_deep_analysis>
type AIWeeklyMoodDeepAnalysis struct {
	ID                              uint           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID                          uint           `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	AnalysisWeek                    time.Time      `gorm:"column:analysis_week;type:date;not null" json:"analysis_week"`
	HiddenEmotionalPatterns         datatypes.JSON `gorm:"column:hidden_emotional_patterns;type:jsonb" json:"hidden_emotional_patterns"`
	UnconsciousTriggers             datatypes.JSON `gorm:"column:unconscious_triggers;type:jsonb" json:"unconscious_triggers"`
	EmotionalCycles                 string         `gorm:"column:emotional_cycles;type:text[]" json:"emotional_cycles"`
	UnmetNeeds                      string         `gorm:"column:unmet_needs;type:text[]" json:"unmet_needs"`
	ValuesInConflict                datatypes.JSON `gorm:"column:values_in_conflict;type:jsonb" json:"values_in_conflict"`
	ValuesBeingHonored              datatypes.JSON `gorm:"column:values_being_honored;type:jsonb" json:"values_being_honored"`
	DeepInsights                    string         `gorm:"column:deep_insights;type:text" json:"deep_insights"`
	RecommendedActions              string         `gorm:"column:recommended_actions;type:text[]" json:"recommended_actions"`
	SuggestedLessonIds              string         `gorm:"column:suggested_lesson_ids;type:bigint[]" json:"suggested_lesson_ids"`
	ConsciousnessShiftOpportunities string         `gorm:"column:consciousness_shift_opportunities;type:text[]" json:"consciousness_shift_opportunities"`
	CreatedAt                       time.Time      `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	User                            *Users         `gorm:"foreignKey:user_id;references:id" json:"User"`
}

// TableName AIWeeklyMoodDeepAnalysis's table name
func (*AIWeeklyMoodDeepAnalysis) TableName() string {
	return TableNameAIWeeklyMoodDeepAnalysis
}
