// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGoalMilestones = "mindstep.goal_milestones"

// GoalMilestones mapped from table <mindstep.goal_milestones>
type GoalMilestones struct {
	ID          uint      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	GoalID      uint      `gorm:"column:goal_id;type:bigint;not null" json:"goal_id"`
	Title       string    `gorm:"column:title;type:character varying(255);not null" json:"title"`
	Description string    `gorm:"column:description;type:text" json:"description"`
	TargetDate  time.Time `gorm:"column:target_date;type:date" json:"target_date"`
	IsCompleted bool      `gorm:"column:is_completed;type:boolean" json:"is_completed"`
	CompletedAt time.Time `gorm:"column:completed_at;type:timestamp without time zone" json:"completed_at"`
	SortOrder   int       `gorm:"column:sort_order;type:integer" json:"sort_order"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	Goal        *Goals    `gorm:"foreignKey:goal_id;references:id" json:"Goal"`
}

// TableName GoalMilestones's table name
func (*GoalMilestones) TableName() string {
	return TableNameGoalMilestones
}
