// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMoodCategories = "mood_categories"

// MoodCategories mapped from table <mood_categories>
type MoodCategories struct {
	ID        uint      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;type:character varying(50);not null" json:"name"`
	Color     string    `gorm:"column:color;type:character varying(7)" json:"color"`
	Icon      string    `gorm:"column:icon;type:character varying(50)" json:"icon"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
}

// TableName MoodCategories's table name
func (*MoodCategories) TableName() string {
	return TableNameMoodCategories
}
