// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMoods = "moods"

// Moods mapped from table <moods>
type Moods struct {
	ID             uint            `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	CategoryID     uint            `gorm:"column:category_id;type:integer;not null" json:"category_id"`
	Name           string          `gorm:"column:name;type:character varying(50);not null" json:"name"`
	Description    string          `gorm:"column:description;type:text" json:"description"`
	IntensityLevel *int            `gorm:"column:intensity_level;type:integer" json:"intensity_level"`
	Emoji          string          `gorm:"column:emoji;type:character varying(10)" json:"emoji"`
	CreatedAt      time.Time       `gorm:"column:created_at;type:timestamp without time zone;default:now()" json:"created_at"`
	Category       *MoodCategories `gorm:"foreignKey:category_id;references:id" json:"category"`
}

// TableName Moods's table name
func (*Moods) TableName() string {
	return TableNameMoods
}
