// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRoleOwners = "role_owners"

// RoleOwners mapped from table <role_owners>
type RoleOwners struct {
	ID          uint      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	RoleID      uint      `gorm:"column:role_id;type:bigint;not null" json:"role_id"`
	OwnerID     uint      `gorm:"column:owner_id;type:bigint;not null" json:"owner_id"`
	CreatedByID uint      `gorm:"column:created_by_id;type:bigint" json:"created_by_id"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	Status      string    `gorm:"column:status;type:character varying(10)" json:"status"`
	Role        *Roles    `gorm:"foreignKey:role_id;references:id" json:"Role"`
	User        *Users    `gorm:"foreignKey:owner_id;references:id" json:"User"`
}

// TableName RoleOwners's table name
func (*RoleOwners) TableName() string {
	return TableNameRoleOwners
}
