@startuml
left to right direction
skinparam shadowing false
skinparam ActorStyle awesome
skinparam usecase {
  BackgroundColor #F1EFE8
  BorderColor #5F5E5A
  ArrowColor #5F5E5A
}

actor "Хэрэглэгч" as User

rectangle "Тэмдэглэлийн систем" {
  usecase "Тэмдэглэл бичих"              as UC1
  usecase "Тэмдэглэлийн шинжилгээ харах" as UC2
  usecase "Тэмдэглэл жагсаах, устгах, хайх"            as UC3
  usecase "Паттерн шинжилгээ хүсэх"      as UC6
  usecase "Мэдэгдэл хүлээн авах"         as UC7
  usecase "Үнэт зүйлийн граф харах"      as UC8
  usecase "Сэтгэл хөдлөлийн граф харах"  as UC9
}

User --> UC1
User --> UC3
User --> UC6
User --> UC8
User --> UC9

UC1 .> UC2 : <<include>>
UC6 .> UC7 : <<include>>

@enduml